from typing import List

class WasmRuntime:
    def __init__(self):
        self.code = []
        self.indent = 0

    def emit(self, line: str = ""):
        indent = "  " * self.indent
        self.code.append(f"{indent}{line}")

    def generate(self) -> str:
        self.code = []
        self.emit(';; KentScript WASM Runtime')
        self.emit()
        self._emit_wasi_imports()
        self._emit_memory()
        self._emit_allocator()
        self._emit_print_helpers()
        self._emit_string_ops()
        self._emit_array_ops()
        self._emit_struct_ops()
        self._emit_dict_ops()
        self._emit_math_helpers()
        self._emit_type_conversions()
        return '\n'.join(self.code)

    def _emit_wasi_imports(self):
        self.emit('(import "wasi_unstable" "fd_write"')
        self.emit('  (func $fd_write (param i32 i32 i32 i32) (result i32))')
        self.emit(')')
        self.emit('(import "wasi_unstable" "fd_read"')
        self.emit('  (func $fd_read (param i32 i32 i32 i32) (result i32))')
        self.emit(')')
        self.emit('(import "wasi_unstable" "proc_exit"')
        self.emit('  (func $proc_exit (param i32))')
        self.emit(')')
        self.emit('(import "wasi_unstable" "clock_time_get"')
        self.emit('  (func $clock_time_get (param i32 i64 i32) (result i32))')
        self.emit(')')
        self.emit()

    def _emit_memory(self):
        self.emit('(memory (export "memory") 2)')
        self.emit()

    def _emit_allocator(self):
        self.emit(';; Bump allocator')
        self.emit('(global $__ks_heap_ptr (mut i32) (i32.const 4096))')
        self.emit('(global $__ks_heap_end (mut i32) (i32.const 0))')
        self.emit()
        self.emit('(func $malloc (export "malloc") (param $size i32) (result i32)')
        self.indent += 1
        self.emit('(local $ptr i32)')
        self.emit('global.get $__ks_heap_ptr')
        self.emit('local.set $ptr')
        self.emit('global.get $__ks_heap_ptr')
        self.emit('local.get $size')
        self.emit('i32.add')
        self.emit('global.set $__ks_heap_ptr')
        self.emit('local.get $ptr')
        self.indent -= 1
        self.emit(')')
        self.emit()
        self.emit('(func $free (export "free") (param $ptr i32))')
        self.emit()

    def _emit_print_helpers(self):
        self.emit(';; Print helpers')
        self.emit()

        self.emit('(func $__ks_print_i32 (export "__ks_print_i32") (param $val i32)')
        self.indent += 1
        self.emit('(local $div i32) (local $digits i32) (local $i i32) (local $neg i32) (local $buf i32) (local $ch i32)')
        self.emit('local.get $val')
        self.emit('i32.const 0')
        self.emit('i32.lt_s')
        self.emit('local.set $neg')
        self.emit('i32.const 48')
        self.emit('call $malloc')
        self.emit('local.set $buf')
        self.emit('local.get $neg')
        self.emit('if')
        self.indent += 1
        self.emit('local.get $buf')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('i32.const 45')
        self.emit('i32.store8')
        self.emit('local.get $val')
        self.emit('i32.const -1')
        self.emit('i32.mul')
        self.emit('local.set $val')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $val')
        self.emit('local.set $div')
        self.emit('i32.const 0')
        self.emit('local.set $digits')
        self.emit('block $print_done')
        self.indent += 1
        self.emit('loop $print_loop')
        self.indent += 1
        self.emit('local.get $div')
        self.emit('i32.const 10')
        self.emit('i32.div_u')
        self.emit('local.set $div')
        self.emit('local.get $digits')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.set $digits')
        self.emit('local.get $div')
        self.emit('br_if $print_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $digits')
        self.emit('local.set $i')
        self.emit('block $write_done')
        self.indent += 1
        self.emit('loop $write_loop')
        self.indent += 1
        self.emit('local.get $i')
        self.emit('i32.const 1')
        self.emit('i32.sub')
        self.emit('local.set $i')
        self.emit('local.get $val')
        self.emit('i32.const 10')
        self.emit('i32.div_u')
        self.emit('local.set $div')
        self.emit('local.get $val')
        self.emit('local.get $div')
        self.emit('i32.const 10')
        self.emit('i32.mul')
        self.emit('i32.sub')
        self.emit('i32.const 48')
        self.emit('i32.add')
        self.emit('local.set $ch')
        self.emit('local.get $buf')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $i')
        self.emit('i32.add')
        self.emit('local.get $ch')
        self.emit('i32.store8')
        self.emit('local.get $div')
        self.emit('local.set $val')
        self.emit('local.get $i')
        self.emit('br_if $write_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $neg')
        self.emit('if')
        self.indent += 1
        self.emit('local.get $digits')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.set $digits')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $buf')
        self.emit('local.get $buf')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('i32.store')
        self.emit('local.get $buf')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('local.get $digits')
        self.emit('i32.store')
        self.emit('i32.const 1')
        self.emit('local.get $buf')
        self.emit('i32.const 1')
        self.emit('i32.const 4')
        self.emit('call $fd_write')
        self.emit('drop')
        self.emit('local.get $buf')
        self.emit('call $free')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_print_i64 (export "__ks_print_i64") (param $val i64)')
        self.indent += 1
        self.emit('(local $div i64) (local $digits i64) (local $i i64) (local $neg i32) (local $buf i32) (local $ch i32)')
        self.emit('local.get $val')
        self.emit('i64.const 0')
        self.emit('i64.lt_s')
        self.emit('local.set $neg')
        self.emit('i32.const 72')
        self.emit('call $malloc')
        self.emit('local.set $buf')
        self.emit('local.get $neg')
        self.emit('if')
        self.indent += 1
        self.emit('local.get $buf')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('i32.const 45')
        self.emit('i32.store8')
        self.emit('local.get $val')
        self.emit('i64.const -1')
        self.emit('i64.mul')
        self.emit('local.set $val')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $val')
        self.emit('local.set $div')
        self.emit('i64.const 0')
        self.emit('local.set $digits')
        self.emit('block $print_done')
        self.indent += 1
        self.emit('loop $print_loop')
        self.indent += 1
        self.emit('local.get $div')
        self.emit('i64.const 10')
        self.emit('i64.div_u')
        self.emit('local.set $div')
        self.emit('local.get $digits')
        self.emit('i64.const 1')
        self.emit('i64.add')
        self.emit('local.set $digits')
        self.emit('local.get $div')
        self.emit('i64.const 0')
        self.emit('i64.ne')
        self.emit('br_if $print_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $digits')
        self.emit('local.set $i')
        self.emit('block $write_done')
        self.indent += 1
        self.emit('loop $write_loop')
        self.indent += 1
        self.emit('local.get $i')
        self.emit('i64.const 1')
        self.emit('i64.sub')
        self.emit('local.set $i')
        self.emit('local.get $val')
        self.emit('i64.const 10')
        self.emit('i64.div_u')
        self.emit('local.set $div')
        self.emit('local.get $val')
        self.emit('local.get $div')
        self.emit('i64.const 10')
        self.emit('i64.mul')
        self.emit('i64.sub')
        self.emit('i64.const 48')
        self.emit('i64.add')
        self.emit('i32.wrap_i64')
        self.emit('local.set $ch')
        self.emit('local.get $buf')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $i')
        self.emit('i32.wrap_i64')
        self.emit('i32.add')
        self.emit('local.get $ch')
        self.emit('i32.store8')
        self.emit('local.get $div')
        self.emit('local.set $val')
        self.emit('local.get $i')
        self.emit('i64.const 0')
        self.emit('i64.ne')
        self.emit('br_if $write_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $neg')
        self.emit('if')
        self.indent += 1
        self.emit('local.get $digits')
        self.emit('i64.const 1')
        self.emit('i64.add')
        self.emit('local.set $digits')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $buf')
        self.emit('local.get $buf')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('i32.store')
        self.emit('local.get $buf')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('local.get $digits')
        self.emit('i32.wrap_i64')
        self.emit('i32.store')
        self.emit('i32.const 1')
        self.emit('local.get $buf')
        self.emit('i32.const 1')
        self.emit('i32.const 4')
        self.emit('call $fd_write')
        self.emit('drop')
        self.emit('local.get $buf')
        self.emit('call $free')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_print_f64 (export "__ks_print_f64") (param $val f64)')
        self.indent += 1
        self.emit('(local $ival i32)')
        self.emit('local.get $val')
        self.emit('i32.trunc_f64_s')
        self.emit('local.set $ival')
        self.emit('local.get $ival')
        self.emit('call $__ks_print_i32')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_print_str (export "__ks_print_str")')
        self.emit('  (param $ptr i32) (param $len i32)')
        self.indent += 1
        self.emit('(local $iov i32)')
        self.emit('i32.const 16')
        self.emit('call $malloc')
        self.emit('local.set $iov')
        self.emit('local.get $iov')
        self.emit('local.get $ptr')
        self.emit('i32.store')
        self.emit('local.get $iov')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('local.get $len')
        self.emit('i32.store')
        self.emit('i32.const 1')
        self.emit('local.get $iov')
        self.emit('i32.const 1')
        self.emit('i32.const 4')
        self.emit('call $fd_write')
        self.emit('drop')
        self.emit('local.get $iov')
        self.emit('call $free')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_print_str_ptr (export "__ks_print_str_ptr") (param $ptr i32)')
        self.indent += 1
        self.emit('(local $len i32)')
        self.emit('local.get $ptr')
        self.emit('call $__ks_strlen')
        self.emit('local.set $len')
        self.emit('local.get $ptr')
        self.emit('local.get $len')
        self.emit('call $__ks_print_str')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_print_char (export "__ks_print_char") (param $ch i32)')
        self.indent += 1
        self.emit('(local $iov i32)')
        self.emit('i32.const 16')
        self.emit('call $malloc')
        self.emit('local.set $iov')
        self.emit('local.get $iov')
        self.emit('i32.const 8')
        self.emit('i32.store')
        self.emit('local.get $iov')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('i32.const 1')
        self.emit('i32.store')
        self.emit('i32.const 8')
        self.emit('local.get $ch')
        self.emit('i32.store8')
        self.emit('i32.const 1')
        self.emit('local.get $iov')
        self.emit('i32.const 1')
        self.emit('i32.const 4')
        self.emit('call $fd_write')
        self.emit('drop')
        self.emit('local.get $iov')
        self.emit('call $free')
        self.indent -= 1
        self.emit(')')
        self.emit()

    def _emit_string_ops(self):
        self.emit(';; String operations')
        self.emit('(func $__ks_strlen (export "__ks_strlen") (param $ptr i32) (result i32)')
        self.indent += 1
        self.emit('(local $len i32)')
        self.emit('block $strlen_done')
        self.indent += 1
        self.emit('loop $strlen_loop')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('local.get $len')
        self.emit('i32.add')
        self.emit('i32.load8_u')
        self.emit('i32.eqz')
        self.emit('br_if $strlen_done')
        self.emit('local.get $len')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.set $len')
        self.emit('br $strlen_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $len')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_strcmp (export "__ks_strcmp") (param $a i32) (param $b i32) (result i32)')
        self.indent += 1
        self.emit('(local $ca i32) (local $cb i32)')
        self.emit('block $cmp_done')
        self.indent += 1
        self.emit('loop $cmp_loop')
        self.indent += 1
        self.emit('local.get $a')
        self.emit('i32.load8_u')
        self.emit('local.set $ca')
        self.emit('local.get $b')
        self.emit('i32.load8_u')
        self.emit('local.set $cb')
        self.emit('local.get $ca')
        self.emit('local.get $cb')
        self.emit('i32.ne')
        self.emit('br_if $cmp_done')
        self.emit('local.get $ca')
        self.emit('i32.eqz')
        self.emit('br_if $cmp_done')
        self.emit('local.get $a')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.set $a')
        self.emit('local.get $b')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.set $b')
        self.emit('br $cmp_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $ca')
        self.emit('local.get $cb')
        self.emit('i32.sub')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_str_concat (export "__ks_str_concat") (param $a i32) (param $b i32) (result i32)')
        self.indent += 1
        self.emit('(local $la i32) (local $lb i32) (local $result i32)')
        self.emit('local.get $a')
        self.emit('call $__ks_strlen')
        self.emit('local.set $la')
        self.emit('local.get $b')
        self.emit('call $__ks_strlen')
        self.emit('local.set $lb')
        self.emit('local.get $la')
        self.emit('local.get $lb')
        self.emit('i32.add')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('call $malloc')
        self.emit('local.set $result')
        self.emit('local.get $result')
        self.emit('local.get $a')
        self.emit('local.get $la')
        self.emit('call $memcpy')
        self.emit('local.get $result')
        self.emit('local.get $la')
        self.emit('i32.add')
        self.emit('local.get $b')
        self.emit('local.get $lb')
        self.emit('call $memcpy')
        self.emit('local.get $result')
        self.emit('local.get $la')
        self.emit('i32.add')
        self.emit('local.get $lb')
        self.emit('i32.add')
        self.emit('i32.const 0')
        self.emit('i32.store8')
        self.emit('local.get $result')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $memcpy (export "memcpy") (param $dst i32) (param $src i32) (param $len i32)')
        self.indent += 1
        self.emit('(local $i i32)')
        self.emit('block $cpy_done')
        self.indent += 1
        self.emit('loop $cpy_loop')
        self.indent += 1
        self.emit('local.get $i')
        self.emit('local.get $len')
        self.emit('i32.ge_u')
        self.emit('br_if $cpy_done')
        self.emit('local.get $dst')
        self.emit('local.get $i')
        self.emit('i32.add')
        self.emit('local.get $src')
        self.emit('local.get $i')
        self.emit('i32.add')
        self.emit('i32.load8_u')
        self.emit('i32.store8')
        self.emit('local.get $i')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.set $i')
        self.emit('br $cpy_loop')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit(')')
        self.emit()

    def _emit_array_ops(self):
        self.emit(';; Array/list operations')
        self.emit('(func $__ks_list_new (export "__ks_list_new") (param $count i32) (result i32)')
        self.indent += 1
        self.emit('(local $ptr i32)')
        self.emit('local.get $count')
        self.emit('i32.const 3')
        self.emit('i32.shl')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('call $malloc')
        self.emit('local.set $ptr')
        self.emit('local.get $ptr')
        self.emit('local.get $count')
        self.emit('i32.store')
        self.emit('local.get $ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('local.get $count')
        self.emit('i32.store')
        self.emit('local.get $ptr')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_list_len (export "__ks_list_len") (param $ptr i32) (result i32)')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('i32.load')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_list_get (export "__ks_list_get") (param $ptr i32) (param $idx i32) (result i64)')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 3')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('i64.load')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_list_set (export "__ks_list_set") (param $ptr i32) (param $idx i32) (param $val i64)')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 3')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('local.get $val')
        self.emit('i64.store')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_list_append (export "__ks_list_append") (param $ptr i32) (param $val i64)')
        self.indent += 1
        self.emit('(local $len i32) (local $cap i32)')
        self.emit('local.get $ptr')
        self.emit('i32.load')
        self.emit('local.set $len')
        self.emit('local.get $ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('i32.load')
        self.emit('local.set $cap')
        self.emit('local.get $len')
        self.emit('local.get $cap')
        self.emit('i32.ge_u')
        self.emit('if')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('local.get $cap')
        self.emit('i32.const 2')
        self.emit('i32.mul')
        self.emit('i32.const 3')
        self.emit('i32.shl')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('call $__ks_realloc')
        self.emit('local.set $ptr')
        self.emit('local.get $ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('local.get $cap')
        self.emit('i32.const 2')
        self.emit('i32.mul')
        self.emit('i32.store')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $len')
        self.emit('i32.const 3')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('local.get $val')
        self.emit('i64.store')
        self.emit('local.get $ptr')
        self.emit('local.get $len')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('i32.store')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_realloc (export "__ks_realloc") (param $old_ptr i32) (param $new_size i32) (result i32)')
        self.indent += 1
        self.emit('(local $new_ptr i32) (local $old_size i32)')
        self.emit('local.get $new_size')
        self.emit('call $malloc')
        self.emit('local.set $new_ptr')
        self.emit('local.get $old_ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('i32.load')
        self.emit('local.set $old_size')
        self.emit('local.get $old_size')
        self.emit('i32.const 3')
        self.emit('i32.shl')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.set $old_size')
        self.emit('local.get $new_ptr')
        self.emit('local.get $old_ptr')
        self.emit('local.get $old_size')
        self.emit('call $memcpy')
        self.emit('local.get $new_ptr')
        self.indent -= 1
        self.emit(')')
        self.emit()

    def _emit_struct_ops(self):
        self.emit(';; Struct operations')
        self.emit('(func $__ks_struct_new (export "__ks_struct_new") (param $size i32) (result i32)')
        self.indent += 1
        self.emit('local.get $size')
        self.emit('call $malloc')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_struct_get (export "__ks_struct_get") (param $ptr i32) (param $offset i32) (result i64)')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('local.get $offset')
        self.emit('i32.add')
        self.emit('i64.load')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_struct_set (export "__ks_struct_set") (param $ptr i32) (param $offset i32) (param $val i64)')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('local.get $offset')
        self.emit('i32.add')
        self.emit('local.get $val')
        self.emit('i64.store')
        self.indent -= 1
        self.emit(')')
        self.emit()

    def _emit_dict_ops(self):
        self.emit(';; Dict operations (linear probing hash table)')
        self.emit('(global $__ks_dict_cap (mut i32) (i32.const 0))')
        self.emit()
        self.emit('(func $__ks_dict_new (export "__ks_dict_new") (param $cap i32) (result i32)')
        self.indent += 1
        self.emit('(local $ptr i32)')
        self.emit('local.get $cap')
        self.emit('i32.const 4')
        self.emit('i32.shl')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('call $malloc')
        self.emit('local.set $ptr')
        self.emit('local.get $ptr')
        self.emit('i32.const 0')
        self.emit('i32.store')
        self.emit('local.get $ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('local.get $cap')
        self.emit('i32.store')
        self.emit('local.get $ptr')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_dict_hash (export "__ks_dict_hash") (param $key i64) (result i32)')
        self.indent += 1
        self.emit('local.get $key')
        self.emit('i32.wrap_i64')
        self.emit('i32.const 2654435761')
        self.emit('i32.mul')
        self.emit('i32.const 16')
        self.emit('i32.shr_u')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_dict_set (export "__ks_dict_set") (param $ptr i32) (param $key i64) (param $val i64)')
        self.indent += 1
        self.emit('(local $cap i32) (local $idx i32) (local $ekey i64)')
        self.emit('local.get $ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('i32.load')
        self.emit('local.set $cap')
        self.emit('local.get $key')
        self.emit('call $__ks_dict_hash')
        self.emit('local.get $cap')
        self.emit('i32.rem_u')
        self.emit('local.set $idx')
        self.emit('block $set_done')
        self.indent += 1
        self.emit('loop $set_probe')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 4')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('i64.load')
        self.emit('local.set $ekey')
        self.emit('local.get $ekey')
        self.emit('i64.eqz')
        self.emit('br_if $set_done')
        self.emit('local.get $ekey')
        self.emit('local.get $key')
        self.emit('i64.eq')
        self.emit('br_if $set_done')
        self.emit('local.get $idx')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.get $cap')
        self.emit('i32.rem_u')
        self.emit('local.set $idx')
        self.emit('br $set_probe')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 4')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('local.get $key')
        self.emit('i64.store')
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 4')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $val')
        self.emit('i64.store')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $__ks_dict_get (export "__ks_dict_get") (param $ptr i32) (param $key i64) (result i64)')
        self.indent += 1
        self.emit('(local $cap i32) (local $idx i32) (local $ekey i64)')
        self.emit('local.get $ptr')
        self.emit('i32.const 4')
        self.emit('i32.add')
        self.emit('i32.load')
        self.emit('local.set $cap')
        self.emit('local.get $key')
        self.emit('call $__ks_dict_hash')
        self.emit('local.get $cap')
        self.emit('i32.rem_u')
        self.emit('local.set $idx')
        self.emit('block $get_done')
        self.indent += 1
        self.emit('loop $get_probe')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 4')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('i64.load')
        self.emit('local.set $ekey')
        self.emit('local.get $ekey')
        self.emit('i64.eqz')
        self.emit('br_if $get_done')
        self.emit('local.get $ekey')
        self.emit('local.get $key')
        self.emit('i64.eq')
        self.emit('if')
        self.indent += 1
        self.emit('local.get $ptr')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('local.get $idx')
        self.emit('i32.const 4')
        self.emit('i32.shl')
        self.emit('i32.add')
        self.emit('i32.const 8')
        self.emit('i32.add')
        self.emit('i64.load')
        self.indent -= 1
        self.emit('return')
        self.emit('end')
        self.emit('local.get $idx')
        self.emit('i32.const 1')
        self.emit('i32.add')
        self.emit('local.get $cap')
        self.emit('i32.rem_u')
        self.emit('local.set $idx')
        self.emit('br $get_probe')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit('end')
        self.emit('i64.const 0')
        self.indent -= 1
        self.emit(')')
        self.emit()

    def _emit_math_helpers(self):
        self.emit(';; Math helpers')
        self.emit('(func $abs (export "abs") (param $x i32) (result i32)')
        self.indent += 1
        self.emit('local.get $x')
        self.emit('i32.const 0')
        self.emit('i32.lt_s')
        self.emit('if (result i32)')
        self.indent += 1
        self.emit('local.get $x')
        self.emit('i32.const -1')
        self.emit('i32.mul')
        self.indent -= 1
        self.emit('else')
        self.indent += 1
        self.emit('local.get $x')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $max (export "max") (param $a i32) (param $b i32) (result i32)')
        self.indent += 1
        self.emit('local.get $a')
        self.emit('local.get $b')
        self.emit('i32.gt_s')
        self.emit('if (result i32)')
        self.indent += 1
        self.emit('local.get $a')
        self.indent -= 1
        self.emit('else')
        self.indent += 1
        self.emit('local.get $b')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $min (export "min") (param $a i32) (param $b i32) (result i32)')
        self.indent += 1
        self.emit('local.get $a')
        self.emit('local.get $b')
        self.emit('i32.lt_s')
        self.emit('if (result i32)')
        self.indent += 1
        self.emit('local.get $a')
        self.indent -= 1
        self.emit('else')
        self.indent += 1
        self.emit('local.get $b')
        self.indent -= 1
        self.emit('end')
        self.indent -= 1
        self.emit(')')
        self.emit()

    def _emit_type_conversions(self):
        self.emit(';; Type conversions')
        self.emit('(func $i32_to_f64 (export "i32_to_f64") (param i32) (result f64)')
        self.indent += 1
        self.emit('local.get 0')
        self.emit('f64.convert_i32_s')
        self.indent -= 1
        self.emit(')')
        self.emit()

        self.emit('(func $f64_to_i32 (export "f64_to_i32") (param f64) (result i32)')
        self.indent += 1
        self.emit('local.get 0')
        self.emit('i32.trunc_f64_s')
        self.indent -= 1
        self.emit(')')
        self.emit()
