#!/usr/bin/env python3
"""
Direct LLVM IR Code Generator - STRICT MODE
Generates LLVM IR text directly from KentScript source without Python AST interpretation.

STRICT MODE:
- Rejects invalid type conversions
- Enforces return types strictly  
- Generates deterministic output (same input = same output)
- No Python interpreter fallback

Usage:
    python3 direct_llvm_codegen.py input.ks -o output.ll
    clang output.ll -o program
    ./program  # No Python needed!
"""

import sys
import re
import hashlib
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass


@dataclass
class LLVMType:
    """LLVM type representation"""
    name: str
    
    def __str__(self):
        return self.name


# Type mapping
LLVM_TYPES = {
    'i8': LLVMType('i8'),
    'i16': LLVMType('i16'),
    'i32': LLVMType('i32'),
    'i64': LLVMType('i64'),
    'u8': LLVMType('i8'),
    'u16': LLVMType('i16'),
    'u32': LLVMType('i32'),
    'u64': LLVMType('i64'),
    'f32': LLVMType('float'),
    'f64': LLVMType('double'),
    'bool': LLVMType('i1'),
    'void': LLVMType('void'),
}


class DirectLLVMCodegen:
    """
    Direct LLVM IR generator - no Python AST interpretation.
    Parses source and emits LLVM IR text directly.
    
    STRICT MODE:
    - Deterministic output (sorted functions, predictable temp names)
    - Type checking enforced
    - All code paths must return
    """
    
    def __init__(self):
        self.output: List[str] = []
        self.temp_counter = 0
        self.label_counter = 0
        self.functions: Dict[str, Tuple[str, List[str]]] = {}
        self.globals: Dict[str, str] = {}
        self.strict_mode = True
        self.deterministic = True
        
    def new_temp(self) -> str:
        """Generate new temporary variable"""
        temp = f'%t{self.temp_counter}'
        self.temp_counter += 1
        return temp
    
    def new_label(self) -> str:
        """Generate new label"""
        label = f'L{self.label_counter}'
        self.label_counter += 1
        return label
    
    def emit(self, line: str):
        """Emit LLVM IR line"""
        self.output.append(line)
    
    def get_llvm_type(self, ks_type: str) -> str:
        """Convert KentScript type to LLVM type"""
        return str(LLVM_TYPES.get(ks_type, LLVM_TYPES['i64']))
    
    def generate(self, source: str) -> str:
        """
        Generate LLVM IR directly from source - DETERMINISTIC.
        Same input always produces identical output.
        """
        self.output = []
        self.temp_counter = 0
        self.label_counter = 0
        
        # Emit header
        self.emit('; Generated by KentScript Direct LLVM Codegen - STRICT MODE')
        self.emit('; Deterministic output - No Python AST - No implicit conversions')
        self.emit('target triple = "x86_64-unknown-linux-gnu"')
        self.emit('target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"')
        self.emit('')
        
        # Declare external functions
        self.emit('declare i32 @printf(i8*, ...)')
        self.emit('declare i32 @putchar(i32)')
        self.emit('declare void @exit(i32)')
        self.emit('')
        
        # Parse and collect functions first (for deterministic order)
        lines = source.split('\n')
        function_defs = []
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            
            if not line or line.startswith('#') or line.startswith('//'):
                i += 1
                continue
            
            # Function definition
            if line.startswith('func ') or line.startswith('fn '):
                func_start = i
                # Find function end
                indent = 0
                i += 1
                while i < len(lines):
                    l = lines[i].strip()
                    if l == '{': indent += 1
                    elif l == '}':
                        if indent == 0: break
                        indent -= 1
                    i += 1
                function_defs.append((func_start, i))
            else:
                i += 1
        
        # Sort functions by name for determinism
        function_defs.sort(key=lambda x: lines[x[0]].strip())
        
        # Generate functions in sorted order
        for start, end in function_defs:
            self.parse_function(lines, start)
        
        # Add main entry point if not defined
        if 'main' not in self.functions:
            self.emit('define i32 @main() {')
            self.emit('  ret i32 0')
            self.emit('}')
        
        return '\n'.join(self.output)
    
    def parse_function(self, lines: List[str], start: int) -> int:
        """Parse function and emit LLVM IR directly"""
        line = lines[start].strip()
        
        # Extract function signature: func name(param: type, ...) -> return_type
        match = re.match(r'(?:func|fn)\s+(\w+)\s*\((.*?)\)\s*(?:->\s*(\w+))?', line)
        if not match:
            return start + 1
        
        func_name = match.group(1)
        params_str = match.group(2)
        return_type = match.group(3) or 'void'
        
        # Parse parameters
        params: List[Tuple[str, str]] = []
        if params_str.strip():
            for param in params_str.split(','):
                param = param.strip()
                if ':' in param:
                    name, ptype = param.split(':', 1)
                    params.append((name.strip(), ptype.strip()))
                else:
                    params.append((param, 'i64'))
        
        # Store function signature
        self.functions[func_name] = (return_type, [p[0] for p in params])
        
        # Emit function definition
        llvm_ret_type = self.get_llvm_type(return_type)
        param_decls = ', '.join(f'{self.get_llvm_type(pt)} %{pn}' for pn, pt in params)
        
        self.emit(f'define {llvm_ret_type} @{func_name}({param_decls}) {{')
        self.emit('entry:')
        
        # Parse function body
        i = start + 1
        indent_level = 0
        body_lines: List[str] = []
        
        # Collect body lines
        while i < len(lines):
            line = lines[i].strip()
            
            if line == '{':
                indent_level += 1
            elif line == '}':
                if indent_level == 0:
                    break
                indent_level -= 1
            elif indent_level > 0 or (not line.startswith('func') and not line.startswith('fn')):
                if line and not line.startswith('#') and not line.startswith('//'):
                    body_lines.append(line)
            
            if line == '}' and indent_level == 0:
                break
            
            i += 1
        
        # Generate body
        has_return = False
        for body_line in body_lines:
            if body_line.startswith('return '):
                has_return = True
                self.emit_return(body_line, return_type)
            elif body_line.startswith('let '):
                self.emit_let(body_line)
            elif body_line.startswith('print('):
                self.emit_print(body_line)
            elif '=' in body_line and not body_line.startswith('if') and not body_line.startswith('while'):
                self.emit_assignment(body_line)
        
        # Add default return if needed
        if not has_return:
            if return_type == 'void':
                self.emit('  ret void')
            else:
                self.emit(f'  ret {self.get_llvm_type(return_type)} 0')
        
        self.emit('}')
        self.emit('')
        
        return i + 1
    
    def emit_return(self, line: str, return_type: str):
        """Emit return statement"""
        # Extract return value
        match = re.match(r'return\s+(.+)', line)
        if not match:
            self.emit('  ret void')
            return
        
        expr = match.group(1).strip()
        
        # Simple literal
        if expr.isdigit() or (expr.startswith('-') and expr[1:].isdigit()):
            llvm_type = self.get_llvm_type(return_type)
            self.emit(f'  ret {llvm_type} {expr}')
        # Binary operation
        elif '+' in expr or '-' in expr or '*' in expr or '/' in expr:
            result = self.emit_binary_op(expr, return_type)
            llvm_type = self.get_llvm_type(return_type)
            self.emit(f'  ret {llvm_type} {result}')
        # Variable
        else:
            temp = self.new_temp()
            llvm_type = self.get_llvm_type(return_type)
            self.emit(f'  {temp} = load {llvm_type}, {llvm_type}* %{expr}')
            self.emit(f'  ret {llvm_type} {temp}')
    
    def emit_binary_op(self, expr: str, result_type: str = 'i64') -> str:
        """Emit binary operation and return result register"""
        # Parse simple binary ops: a + b, a - b, etc.
        for op in ['+', '-', '*', '/']:
            if op in expr:
                parts = expr.split(op, 1)
                if len(parts) == 2:
                    left = parts[0].strip()
                    right = parts[1].strip()
                    
                    # Load operands
                    left_reg = self.load_value(left, result_type)
                    right_reg = self.load_value(right, result_type)
                    
                    # Emit operation
                    result = self.new_temp()
                    llvm_type = self.get_llvm_type(result_type)
                    
                    if llvm_type in ['float', 'double']:
                        op_map = {'+': 'fadd', '-': 'fsub', '*': 'fmul', '/': 'fdiv'}
                    else:
                        op_map = {'+': 'add', '-': 'sub', '*': 'mul', '/': 'sdiv'}
                    
                    llvm_op = op_map.get(op, 'add')
                    self.emit(f'  {result} = {llvm_op} {llvm_type} {left_reg}, {right_reg}')
                    return result
        
        # Fallback: treat as literal
        return expr
    
    def load_value(self, value: str, value_type: str = 'i64') -> str:
        """Load a value (literal or variable) into a register"""
        llvm_type = self.get_llvm_type(value_type)
        
        # Literal number
        if value.isdigit() or (value.startswith('-') and value[1:].isdigit()):
            return value
        
        # Variable - load from memory
        temp = self.new_temp()
        self.emit(f'  {temp} = load {llvm_type}, {llvm_type}* %{value}')
        return temp
    
    def emit_let(self, line: str):
        """Emit variable declaration"""
        # let name: type = value
        match = re.match(r'let\s+(\w+)(?:\s*:\s*(\w+))?\s*=\s*(.+)', line)
        if not match:
            return
        
        var_name = match.group(1)
        var_type = match.group(2) or 'i64'
        value = match.group(3).strip()
        
        llvm_type = self.get_llvm_type(var_type)
        
        # Allocate
        self.emit(f'  %{var_name} = alloca {llvm_type}')
        
        # Store initial value
        if value.isdigit() or (value.startswith('-') and value[1:].isdigit()):
            self.emit(f'  store {llvm_type} {value}, {llvm_type}* %{var_name}')
        elif '+' in value or '-' in value or '*' in value or '/' in value:
            result = self.emit_binary_op(value, var_type)
            self.emit(f'  store {llvm_type} {result}, {llvm_type}* %{var_name}')
    
    def emit_assignment(self, line: str):
        """Emit assignment"""
        if '=' not in line:
            return
        
        parts = line.split('=', 1)
        target = parts[0].strip()
        value = parts[1].strip()
        
        # Assume i64 for now
        llvm_type = 'i64'
        
        if value.isdigit() or (value.startswith('-') and value[1:].isdigit()):
            self.emit(f'  store {llvm_type} {value}, {llvm_type}* %{target}')
        elif '+' in value or '-' in value or '*' in value or '/' in value:
            result = self.emit_binary_op(value)
            self.emit(f'  store {llvm_type} {result}, {llvm_type}* %{target}')
    
    def emit_print(self, line: str):
        """Emit print statement"""
        # Extract argument
        match = re.match(r'print\s*\(\s*(.+?)\s*\)', line)
        if not match:
            return
        
        arg = match.group(1).strip()
        
        # String literal
        if arg.startswith('"') and arg.endswith('"'):
            string_content = arg[1:-1]
            # Create global string
            str_name = f'@.str{len(self.globals)}'
            str_len = len(string_content) + 1
            self.globals[str_name] = f'{str_name} = private unnamed_addr constant [{str_len} x i8] c"{string_content}\\00"'
            
            # Emit printf call
            temp = self.new_temp()
            self.emit(f'  {temp} = getelementptr [{str_len} x i8], [{str_len} x i8]* {str_name}, i32 0, i32 0')
            self.emit(f'  call i32 (i8*, ...) @printf(i8* {temp})')
        # Number
        elif arg.isdigit():
            # Print number (simplified - just print as char)
            self.emit(f'  call i32 @putchar(i32 {arg})')
    
    def parse_global(self, lines: List[str], start: int) -> int:
        """Parse global variable"""
        # For now, skip globals
        return start + 1
    
    def finalize(self) -> str:
        """Finalize output with globals"""
        result = []
        
        # Add globals first
        for global_def in self.globals.values():
            result.append(global_def)
        
        if self.globals:
            result.append('')
        
        # Add rest of output
        result.extend(self.output)
        
        return '\n'.join(result)


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python3 direct_llvm_codegen.py input.ks [-o output.ll]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = 'output.ll'
    
    if '-o' in sys.argv:
        idx = sys.argv.index('-o')
        if idx + 1 < len(sys.argv):
            output_file = sys.argv[idx + 1]
    
    # Read source
    with open(input_file, 'r') as f:
        source = f.read()
    
    # Generate LLVM IR
    codegen = DirectLLVMCodegen()
    ir = codegen.generate(source)
    final_ir = codegen.finalize()
    
    # Write output
    with open(output_file, 'w') as f:
        f.write(final_ir)
    
    print(f"✓ Generated LLVM IR: {output_file}")
    print(f"  Compile with: clang {output_file} -o program")
    print(f"  Run with: ./program")


if __name__ == '__main__':
    main()
