#!/usr/bin/env python3
"""
ks_llvm_builder.py — Real LLVM Toolchain Integration
[KS-REF-070] Build LLVM from source (via cmake + ninja)
[KS-REF-071] IR → optimise → native (LTO / PGO / vectorisation)
[KS-REF-072] Drives clang, llc, opt, lld directly
No wrapper toys — direct subprocess calls to real LLVM tools.
"""

from __future__ import annotations
import os, sys, subprocess, shutil, tempfile, platform, json, textwrap
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Tuple
from enum import Enum

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

class LLVMOptLevel(Enum):
    NONE  = "0"
    LESS  = "1"
    STD   = "2"
    AGGR  = "3"
    SIZE  = "s"
    SIZES = "z"

@dataclass
class LLVMConfig:
    """Full LLVM pipeline configuration"""
    opt_level:     LLVMOptLevel = LLVMOptLevel.AGGR
    enable_lto:    bool  = True      # Link-Time Optimisation
    enable_pgo:    bool  = False     # Profile-Guided (needs profile data)
    pgo_profile:   str   = ""        # Path to .profdata
    enable_vec:    bool  = True      # Auto-vectorisation
    enable_slp:    bool  = True      # SLP vectoriser
    target_cpu:    str   = "native"  # or "x86-64-v3", "cortex-a72", …
    target_triple: str   = ""        # auto-detected if empty
    extra_clang:   List[str] = field(default_factory=list)
    extra_opt:     List[str] = field(default_factory=list)
    extra_link:    List[str] = field(default_factory=list)
    llvm_prefix:   str   = ""        # /usr/lib/llvm-16/bin etc; auto-detected

# ---------------------------------------------------------------------------
# Tool Detection
# ---------------------------------------------------------------------------

def _find_tool(name: str, prefix: str = "") -> Optional[str]:
    """Find an LLVM tool, trying versioned names (clang-17, clang-16, …)"""
    candidates = []
    if prefix:
        candidates.append(os.path.join(prefix, name))
    # Prefer highest version
    for ver in range(20, 13, -1):
        candidates.append(f"{name}-{ver}")
    candidates.append(name)
    for c in candidates:
        path = shutil.which(c)
        if path:
            return path
    return None

def detect_llvm_tools(prefix: str = "") -> Dict[str, str]:
    """Return dict of discovered LLVM tool paths"""
    tools = {}
    for t in ("clang", "clang++", "opt", "llc", "lld", "ld.lld",
              "llvm-ar", "llvm-objcopy", "llvm-strip", "llvm-profdata"):
        path = _find_tool(t, prefix)
        if path:
            tools[t] = path
    return tools

# ---------------------------------------------------------------------------
# IR Emission
# ---------------------------------------------------------------------------

class LLVMIREmitter:
    """
    Wraps the existing KentScript LLVM backend and adds optimisation
    metadata attributes (nounwind, willreturn, nosync, mustprogress).
    """

    def __init__(self, backend=None):
        self._backend = backend  # existing LLVMBackend instance

    def emit_ir(self, ast, config: LLVMConfig, out_path: str) -> str:
        """
        Generate LLVM IR from AST, annotated for aggressive optimisation.
        Returns path to .ll file.
        """
        if self._backend is not None:
            ir_text = self._backend.generate(ast)
        else:
            # Minimal stub IR for testing the pipeline
            ir_text = textwrap.dedent("""                ; Generated by KentScript LLVM IR Emitter
                target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                target triple = "x86_64-unknown-linux-gnu"

                define i64 @ks_main() #0 {
                entry:
                  ret i64 0
                }

                attributes #0 = { nounwind willreturn nosync mustprogress }
            """)

        # Inject target CPU attribute
        cpu_attr = 'mustprogress nounwind willreturn nosync "target-cpu"="{cpu}"'.format(cpu=config.target_cpu)
        ir_text = ir_text.replace(
            "attributes #0 = { nounwind willreturn nosync mustprogress }",
            f"attributes #0 = {{ {cpu_attr} }}"
        )

        Path(out_path).write_text(ir_text, encoding="utf-8")
        return out_path

# ---------------------------------------------------------------------------
# Optimisation Pipeline
# ---------------------------------------------------------------------------

class LLVMOptPipeline:
    """
    Runs:  .ll → opt (O3 + vectorise + LTO prep) → .bc
    Then:  .bc → llc (native object) → ld.lld (final ELF/binary)
    """

    def __init__(self, tools: Dict[str, str], config: LLVMConfig):
        self.tools  = tools
        self.config = config

    def _run(self, cmd: List[str], *, cwd: Optional[str] = None, capture: bool = False) -> Tuple[int, str, str]:
        result = subprocess.run(cmd, cwd=cwd, capture_output=capture, text=True)
        return result.returncode, result.stdout or "", result.stderr or ""

    # -- Step 1: opt ---------------------------------------------------------
    def optimise_ir(self, ir_path: str, bc_path: str) -> bool:
        """Run 'opt' on IR file, produce optimised bitcode."""
        opt = self.tools.get("opt")
        if not opt:
            print("[LLVM] 'opt' not found — skipping IR optimisation pass")
            # copy as-is for llc
            shutil.copy(ir_path, bc_path)
            return True

        cmd = [opt,
               f"-O{self.config.opt_level.value}",
               "--passes=default<O3>"]

        if self.config.enable_vec:
            cmd += ["--vectorize-loops", "--loop-vectorize", "--slp-vectorize"]
        if self.config.enable_lto:
            cmd += ["--lto-newpm-passes=default<O3>"]
        if self.config.enable_pgo and self.config.pgo_profile:
            cmd += [f"--pgo-instrument-path={self.config.pgo_profile}"]

        cmd += self.config.extra_opt
        cmd += ["-o", bc_path, ir_path]

        rc, out, err = self._run(cmd, capture=True)
        if rc != 0:
            print(f"[LLVM][opt] ERROR:\n{err}")
            return False
        return True

    # -- Step 2: llc ---------------------------------------------------------
    def compile_to_object(self, bc_path: str, obj_path: str) -> bool:
        """Run 'llc' to lower bitcode → native object."""
        llc = self.tools.get("llc")
        if not llc:
            print("[LLVM] 'llc' not found — cannot emit native object")
            return False

        cmd = [llc,
               f"-O{self.config.opt_level.value}",
               f"--mcpu={self.config.target_cpu}",
               "--filetype=obj"]

        if self.config.enable_vec:
            cmd += ["--vectorize-loops"]

        if self.config.target_triple:
            cmd += [f"--mtriple={self.config.target_triple}"]

        cmd += ["-o", obj_path, bc_path]

        rc, out, err = self._run(cmd, capture=True)
        if rc != 0:
            print(f"[LLVM][llc] ERROR:\n{err}")
            return False
        return True

    # -- Step 3: LTO link via lld -------------------------------------------
    def link(self, obj_paths: List[str], out_path: str,
             extra_libs: Optional[List[str]] = None) -> bool:
        """Link object files with ld.lld (supports ThinLTO)."""
        lld = self.tools.get("ld.lld") or self.tools.get("lld")
        if not lld:
            print("[LLVM] 'ld.lld' not found — falling back to system linker")
            lld = shutil.which("ld") or "ld"

        cmd = [lld, "--eh-frame-hdr"]

        if self.config.enable_lto:
            cmd += ["--lto-O3", "--thinlto-jobs=all"]

        cmd += obj_paths
        cmd += (extra_libs or [])
        cmd += self.config.extra_link
        cmd += ["-o", out_path]

        rc, out, err = self._run(cmd, capture=True)
        if rc != 0:
            print(f"[LLVM][lld] ERROR:\n{err}")
            return False
        return True

    # -- Full pipeline -------------------------------------------------------
    def compile(self, ir_path: str, out_path: str,
                extra_objs: Optional[List[str]] = None,
                extra_libs: Optional[List[str]] = None) -> bool:
        """ir_path (.ll) → optimised native binary at out_path."""
        with tempfile.TemporaryDirectory(prefix="ks_llvm_") as tmp:
            bc_path  = os.path.join(tmp, "prog.bc")
            obj_path = os.path.join(tmp, "prog.o")

            print(f"[LLVM] Optimising IR  ({self.config.opt_level.name}) …")
            if not self.optimise_ir(ir_path, bc_path):  return False

            print("[LLVM] Lowering to native object …")
            if not self.compile_to_object(bc_path, obj_path): return False

            objs = [obj_path] + (extra_objs or [])
            print(f"[LLVM] Linking → {out_path} …")
            if not self.link(objs, out_path, extra_libs): return False

        print(f"[LLVM] ✓ Binary ready: {out_path}")
        return True

# ---------------------------------------------------------------------------
# PGO helpers
# ---------------------------------------------------------------------------

class PGOWorkflow:
    """Two-pass PGO: instrument → run → merge → re-compile."""

    def __init__(self, tools: Dict[str, str]):
        self.tools = tools

    def instrument(self, src_path: str, inst_bin: str, config: LLVMConfig) -> bool:
        clang = self.tools.get("clang") or self.tools.get("clang++")
        if not clang:
            print("[PGO] clang not found"); return False
        cmd = [clang, f"-O{config.opt_level.value}",
               "-fprofile-generate", src_path, "-o", inst_bin]
        cmd += config.extra_clang
        rc, _, err = subprocess.run(cmd, capture_output=True, text=True,
                                    stdout=subprocess.PIPE, stderr=subprocess.PIPE), 0, ""
        if isinstance(rc, subprocess.CompletedProcess):
            rc, _, err = rc.returncode, rc.stdout, rc.stderr
        return rc == 0

    def merge_profiles(self, raw_dir: str, out_profdata: str) -> bool:
        llvm_profdata = self.tools.get("llvm-profdata")
        if not llvm_profdata:
            print("[PGO] llvm-profdata not found"); return False
        raw_files = list(Path(raw_dir).glob("*.profraw"))
        if not raw_files:
            print("[PGO] No .profraw files found"); return False
        cmd = [llvm_profdata, "merge", "-output", out_profdata] + [str(f) for f in raw_files]
        return subprocess.run(cmd).returncode == 0

    def compile_with_profile(self, src_path: str, out_path: str,
                             profdata: str, config: LLVMConfig) -> bool:
        clang = self.tools.get("clang") or self.tools.get("clang++")
        if not clang: return False
        cfg2 = LLVMConfig(**{**config.__dict__, "enable_pgo": True, "pgo_profile": profdata})
        pipeline = LLVMOptPipeline(self.tools, cfg2)
        # For simplicity: compile directly with clang -fprofile-use
        cmd = [clang, f"-O{config.opt_level.value}",
               f"-fprofile-use={profdata}", src_path, "-o", out_path]
        cmd += config.extra_clang
        return subprocess.run(cmd).returncode == 0

# ---------------------------------------------------------------------------
# LLVM Source Builder (for from-source builds)
# ---------------------------------------------------------------------------

LLVM_CMAKE_OPTS = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DLLVM_ENABLE_PROJECTS=clang;lld",
    "-DLLVM_ENABLE_RUNTIMES=compiler-rt",
    "-DLLVM_TARGETS_TO_BUILD=X86;AArch64;RISCV",
    "-DLLVM_ENABLE_ASSERTIONS=OFF",
    "-DLLVM_ENABLE_LTO=Thin",
    "-DLLVM_ENABLE_ZLIB=ON",
    "-DLLVM_BUILD_LLVM_DYLIB=ON",
    "-DLLVM_LINK_LLVM_DYLIB=ON",
    "-DLLVM_ENABLE_LIBCXX=OFF",
    "-DLLVM_PARALLEL_LINK_JOBS=2",
    "-DCLANG_ENABLE_ARCMT=OFF",
    "-DCLANG_ENABLE_STATIC_ANALYZER=OFF",
]

def build_llvm_from_source(src_dir: str, build_dir: str,
                            install_dir: str, jobs: int = 0) -> bool:
    """
    Run cmake + ninja to build LLVM from source.
    src_dir   = path to llvm-project/llvm (cloned from github)
    build_dir = cmake build directory
    install_dir = prefix for install
    """
    if jobs <= 0:
        import multiprocessing
        jobs = multiprocessing.cpu_count()

    cmake = shutil.which("cmake")
    ninja = shutil.which("ninja") or shutil.which("ninja-build")
    if not cmake:
        print("[LLVM-SRC] cmake not found — cannot build LLVM from source"); return False
    if not ninja:
        print("[LLVM-SRC] ninja not found — install ninja-build"); return False

    Path(build_dir).mkdir(parents=True, exist_ok=True)

    cmake_cmd = [cmake,
                 "-G", "Ninja",
                 f"-DCMAKE_INSTALL_PREFIX={install_dir}",
                 *LLVM_CMAKE_OPTS,
                 src_dir]
    print("[LLVM-SRC] Running cmake …")
    rc = subprocess.run(cmake_cmd, cwd=build_dir).returncode
    if rc != 0: return False

    print(f"[LLVM-SRC] Building with {jobs} jobs …")
    rc = subprocess.run([ninja, "-j", str(jobs)], cwd=build_dir).returncode
    if rc != 0: return False

    print("[LLVM-SRC] Installing …")
    rc = subprocess.run([ninja, "install"], cwd=build_dir).returncode
    if rc != 0: return False

    print(f"[LLVM-SRC] ✓ LLVM installed to {install_dir}")
    return True

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_pipeline(config: Optional[LLVMConfig] = None) -> Optional[LLVMOptPipeline]:
    """Quick factory — detect tools, return pipeline. Returns None if no LLVM found."""
    if config is None:
        config = LLVMConfig()
    tools = detect_llvm_tools(config.llvm_prefix)
    if not tools:
        return None
    return LLVMOptPipeline(tools, config)

def compile_ks_to_native(ir_path: str, out_path: str,
                          config: Optional[LLVMConfig] = None) -> bool:
    """One-shot: .ll IR → optimised native binary."""
    pipeline = get_pipeline(config)
    if pipeline is None:
        print("[LLVM] No LLVM tools found. Install clang+lld or set llvm_prefix.")
        return False
    return pipeline.compile(ir_path, out_path)
