:: dotenv - Load .env files into environment
::
:: Usage:
::   import dotenv;
::   dotenv.load(".env");
::   let key = os.getenv("API_KEY");

let _env_vars = {};

func load(path, override) {
    if override == none { override = true; }
    if path == none { path = ".env"; }

    let content = file_read_all(path);
    if content == none { return 0; }

    let lines = content.split("\n");
    let count = 0;

    for line in lines {
        line = line.trim();
        if line.length == 0 { continue; }
        if line.startsWith("#") { continue; }
        if line.startsWith("::") { continue; }

        let eq = line.indexOf("=");
        if eq == -1 { continue; }

        let key = line.substring(0, eq).trim();
        let val = line.substring(eq + 1).trim();

        if val.startsWith('"') && val.endsWith('"') {
            val = val.substring(1, val.length - 1);
        } elif val.startsWith("'") && val.endsWith("'") {
            val = val.substring(1, val.length - 1);
        }

        let hash = val.indexOf(" #");
        if hash != -1 {
            val = val.substring(0, hash).trim();
        }

        _env_vars[key] = val;
        os.putenv(key, val);
        count = count + 1;
    }

    return count;
}

func get(key, default) {
    if _env_vars[key] != none {
        return _env_vars[key];
    }
    return default;
}

func set(key, value) {
    _env_vars[key] = value;
    os.putenv(key, value);
}

func keys() {
    let result = [];
    for key in _env_vars {
        result.push(key);
    }
    return result;
}

func all() {
    return _env_vars;
}

func save(path) {
    if path == none { path = ".env"; }
    let lines = [":: Generated by dotenv"];
    for key in _env_vars {
        lines.push(key + "=" + _env_vars[key]);
    }
    file_write_all(path, lines.join("\n"));
}

func parse(content) {
    let result = {};
    let lines = content.split("\n");

    for line in lines {
        line = line.trim();
        if line.length == 0 { continue; }
        if line.startsWith("#") { continue; }
        if line.startsWith("::") { continue; }

        let eq = line.indexOf("=");
        if eq == -1 { continue; }

        let key = line.substring(0, eq).trim();
        let val = line.substring(eq + 1).trim();

        if val.startsWith('"') && val.endsWith('"') {
            val = val.substring(1, val.length - 1);
        } elif val.startsWith("'") && val.endsWith("'") {
            val = val.substring(1, val.length - 1);
        }

        result[key] = val;
    }

    return result;
}

export { load, get, set, keys, all, save, parse };
