"""
Enhanced C Transpiler with Standalone Type System
Generates C code that includes ks_typesystem.h for compile-time type checking.
No Python runtime dependency for type enforcement.

STRICT MODE:
- Rejects invalid type conversions
- Enforces return types strictly
- Prevents silent fallthrough
- Generates deterministic output
- No Python interpreter fallback
"""

import sys
import os
import hashlib
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'codegen'))

from c_transpiler import CTranspiler as BaseCTranspiler


class TypedCTranspiler(BaseCTranspiler):
    """
    Enhanced C transpiler that embeds type checking into generated code.
    Uses ks_typesystem.h for compile-time type enforcement.
    
    STRICT MODE - No implicit conversions, exhaustive matching, deterministic output.
    """
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.use_typed_system = True
        self.strict_mode = True
        self.deterministic = True
        self.temp_counter = 0  # Deterministic temp variable names
        
    def reset_state(self):
        """Reset for deterministic output"""
        self.code = []
        self.indent_level = 0
        self.temp_counter = 0
        self.var_types = {}  # Reset variable type tracking
    
    def transpile(self, ast):
        """Generate C code with embedded type system - DETERMINISTIC"""
        # Reset state for deterministic output
        self.reset_state()
        self._deferred_inits = []
        
        # Extract statements from Program object or list
        if hasattr(ast, 'statements'):
            nodes = ast.statements
        elif isinstance(ast, list):
            nodes = ast
        elif hasattr(ast, '__iter__'):
            nodes = list(ast)
        else:
            nodes = [ast]
        
        # Sort AST nodes for deterministic order (enums/structs first, then functions, then rest)
        def sort_key(n):
            node_type = n.__class__.__name__
            if node_type in ('EnumDef', 'Enum_', 'Enum', 'Struct', 'StructDef'):
                return (0, getattr(n, 'name', ''))
            elif node_type in ('FunctionDef', 'Function'):
                return (1, getattr(n, 'name', ''))
            else:
                return (2, getattr(n, 'name', ''))
        nodes = sorted(nodes, key=sort_key)
        
        # Emit header with type system
        self.emit_header()
        
        # Process AST deterministically
        for node in nodes:
            self.transpile_node(node)
        
        # Emit deferred global initializations before main
        if self._deferred_inits:
            self.emit_line('')
            self.emit_line('void _ks_init_globals(void) {')
            self.indent_level += 1
            for var_name, init_val in self._deferred_inits:
                self.emit_line(f'{var_name} = {init_val};')
            self.indent_level -= 1
            self.emit_line('}')
        
        # Generate main function if not present
        has_main = any(getattr(n, 'name', None) == 'main' for n in nodes if n.__class__.__name__ in ('FunctionDef', 'Function'))
        if not has_main:
            self.emit_line('')
            self.emit_line('int main(void) {')
            self.indent_level += 1
            
            if self._deferred_inits:
                self.emit_line('_ks_init_globals();')
            
            # Execute top-level statements
            for node in nodes:
                node_type = node.__class__.__name__
                if node_type not in ('FunctionDef', 'Function', 'EnumDef', 'Enum_', 'Enum', 'Struct', 'StructDef', 'LetDecl', 'VarDecl'):
                    # This is a top-level expression/statement
                    if node_type == 'FunctionCall':
                        func = getattr(node, 'func', None)
                        args = getattr(node, 'args', [])
                        func_name = func.name if hasattr(func, 'name') else str(func)
                        arg_strs = [self.transpile_expression(arg) for arg in args]
                        
                        if func_name == 'print':
                            for arg_str in arg_strs:
                                self.emit_line(f'printf("%s\\n", _ks_str_int({arg_str}));')
                        else:
                            self.emit_line(f'{func_name}({", ".join(arg_strs)});')
            
            self.emit_line('return 0;')
            self.indent_level -= 1
            self.emit_line('}')
        
        return '\n'.join(self.code)
    
    def emit_header(self):
        """Emit C header with standalone type system"""
        self.code.append('/* Generated by KentScript Typed C Transpiler - STRICT MODE */')
        self.code.append('/* Type checking enforced at compile-time by GCC/Clang */')
        self.code.append('/* No implicit conversions - No silent fallthrough - Deterministic output */')
        self.code.append('')
        self.code.append('#include "ks_typesystem.h"')
        self.code.append('#include <stdio.h>')
        self.code.append('#include <stdlib.h>')
        self.code.append('#include <string.h>')
        self.code.append('#include <stdint.h>')
        self.code.append('#include <stdbool.h>')
        self.code.append('')
        self.code.append('/* STRICT MODE: All conversions explicit, all returns checked */')
        self.code.append('')
        
        # Dict helper functions
        self.code.append('/* Dict hash table */')
        self.code.append('typedef struct _ks_dict_node {')
        self.code.append('    char key[64];')
        self.code.append('    long long val;')
        self.code.append('    int is_str;')
        self.code.append('    struct _ks_dict_node* next;')
        self.code.append('} _ks_dict_node;')
        self.code.append('typedef struct { _ks_dict_node* buckets[32]; } _ks_dict;')
        self.code.append('')
        self.code.append('static unsigned int _ks_hash(const char* s) {')
        self.code.append('    unsigned int h = 0;')
        self.code.append('    while (*s) h = h * 31 + *s++;')
        self.code.append('    return h % 32;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static _ks_dict* _ks_dict_new(void) {')
        self.code.append('    _ks_dict* d = malloc(sizeof(_ks_dict));')
        self.code.append('    memset(d, 0, sizeof(_ks_dict));')
        self.code.append('    return d;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static void _ks_dict_set(_ks_dict* d, const char* key, long long val, int is_str) {')
        self.code.append('    unsigned int h = _ks_hash(key);')
        self.code.append('    _ks_dict_node* n = d->buckets[h];')
        self.code.append('    if (!n) {')
        self.code.append('        n = malloc(sizeof(_ks_dict_node));')
        self.code.append('        strncpy(n->key, key, 63); n->key[63] = 0;')
        self.code.append('        n->val = val; n->is_str = is_str; n->next = NULL;')
        self.code.append('        d->buckets[h] = n;')
        self.code.append('    }')
        self.code.append('}')
        self.code.append('')
        self.code.append('static long long _ks_dict_get(_ks_dict* d, const char* key, int* found) {')
        self.code.append('    unsigned int h = _ks_hash(key);')
        self.code.append('    _ks_dict_node* n = d->buckets[h];')
        self.code.append('    if (n && strcmp(n->key, key) == 0) { *found = 1; return n->val; }')
        self.code.append('    *found = 0; return 0;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static long long _ks_dict_get_simple(_ks_dict* d, const char* key) {')
        self.code.append('    int found; return _ks_dict_get(d, key, &found);')
        self.code.append('}')
        self.code.append('')
        self.code.append('static _ks_dict* _ks_dict_create(const char* k1, long long v1, int s1, const char* k2, long long v2, int s2) {')
        self.code.append('    _ks_dict* d = _ks_dict_new();')
        self.code.append('    _ks_dict_set(d, k1, v1, s1);')
        self.code.append('    _ks_dict_set(d, k2, v2, s2);')
        self.code.append('    return d;')
        self.code.append('}')
        self.code.append('')
        
        # I/O support functions
        self.code.append('/* I/O support functions */')
        self.code.append('static int system_file_write_text(const char* path, const char* content) {')
        self.code.append('    FILE* f = fopen(path, "w");')
        self.code.append('    if (!f) return 0;')
        self.code.append('    fputs(content, f);')
        self.code.append('    fclose(f);')
        self.code.append('    return 1;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static int system_file_rename(const char* old_path, const char* new_path) {')
        self.code.append('    return rename(old_path, new_path) == 0;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static int system_file_remove(const char* path) {')
        self.code.append('    return remove(path) == 0;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static int system_subprocess_run(const char* cmd) {')
        self.code.append('    return system(cmd);')
        self.code.append('}')
        self.code.append('')
        
        # Set helper functions
        self.code.append('/* Set hash table */')
        self.code.append('typedef struct _ks_set_node {')
        self.code.append('    long long val;')
        self.code.append('    struct _ks_set_node* next;')
        self.code.append('} _ks_set_node;')
        self.code.append('typedef struct { _ks_set_node* buckets[32]; } _ks_set;')
        self.code.append('')
        self.code.append('static unsigned int _ks_hash_int(long long v) {')
        self.code.append('    return (unsigned int)(v % 32);')
        self.code.append('}')
        self.code.append('')
        self.code.append('static _ks_set* _ks_set_new(void) {')
        self.code.append('    _ks_set* s = malloc(sizeof(_ks_set));')
        self.code.append('    memset(s, 0, sizeof(_ks_set));')
        self.code.append('    return s;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static void _ks_set_add(_ks_set* s, long long val) {')
        self.code.append('    unsigned int h = _ks_hash_int(val);')
        self.code.append('    _ks_set_node* n = s->buckets[h];')
        self.code.append('    while (n) {')
        self.code.append('        if (n->val == val) return;')
        self.code.append('        n = n->next;')
        self.code.append('    }')
        self.code.append('    n = malloc(sizeof(_ks_set_node));')
        self.code.append('    n->val = val; n->next = s->buckets[h];')
        self.code.append('    s->buckets[h] = n;')
        self.code.append('}')
        self.code.append('')
        self.code.append('static int _ks_set_contains(_ks_set* s, long long val) {')
        self.code.append('    unsigned int h = _ks_hash_int(val);')
        self.code.append('    _ks_set_node* n = s->buckets[h];')
        self.code.append('    while (n) {')
        self.code.append('        if (n->val == val) return 1;')
        self.code.append('        n = n->next;')
        self.code.append('    }')
        self.code.append('    return 0;')
        self.code.append('}')
        self.code.append('')
    
    def get_typed_c_type(self, ks_type: str) -> str:
        """Map KentScript type to typed C type from ks_typesystem.h"""
        type_map = {
            'i8': 'ks_i8',
            'i16': 'ks_i16',
            'i32': 'ks_i32',
            'i64': 'ks_i64',
            'u8': 'ks_u8',
            'u16': 'ks_u16',
            'u32': 'ks_u32',
            'u64': 'ks_u64',
            'f32': 'ks_f32',
            'f64': 'ks_f64',
            'bool': 'ks_bool',
            'void': 'ks_void',
        }
        return type_map.get(ks_type, 'ks_i64')
    
    def _infer_type_from_value(self, value) -> str:
        """Infer KentScript type from value expression"""
        if value is None:
            return 'ks_i64'
        
        val_class = value.__class__.__name__
        
        if val_class in ('Number', 'Integer', 'Int', 'FloatLiteral'):
            if hasattr(value, 'is_float') and value.is_float:
                return 'ks_f64'
            return 'ks_i64'
        elif val_class in ('String', 'StringLiteral', 'Str'):
            return 'ks_str'
        elif val_class in ('Boolean', 'BoolLiteral', 'Bool'):
            return 'ks_bool'
        elif val_class in ('ArrayLiteral', 'ListLiteral'):
            return 'ks_i64[]'
        elif val_class in ('Identifier', 'Name'):
            return 'ks_i64'
        elif val_class in ('BinaryOp', 'BinOp'):
            return 'ks_i64'
        elif val_class in ('UnaryOp', 'Unary'):
            return 'ks_i64'
        else:
            return 'ks_i64'
    
    def _is_non_constant_expr(self, value) -> bool:
        """Check if expression is non-constant (cannot be used in global initializer)"""
        if value is None:
            return False
        val_class = value.__class__.__name__
        return val_class in ('FunctionCall', 'BinaryOp', 'CallExpr')
    
    def transpile_function(self, node):
        """Transpile function with STRICT type-safe signature and return checking"""
        func_name = getattr(node, 'name', 'unnamed')
        params = getattr(node, 'params', [])
        return_type = getattr(node, 'return_type', 'i64')
        body = getattr(node, 'body', [])
        
        # Get typed return type
        c_ret_type = self.get_typed_c_type(return_type)
        
        # Build parameter list with types (sorted for determinism)
        param_list = []
        param_names = []
        for param in params:
            if isinstance(param, str):
                param_list.append(f'ks_i64 {param}')
                param_names.append(param)
            elif hasattr(param, 'name'):
                param_name = param.name
                param_type = getattr(param, 'param_type', 'i64')
                c_param_type = self.get_typed_c_type(param_type)
                param_list.append(f'{c_param_type} {param_name}')
                param_names.append(param_name)
        
        params_str = ', '.join(param_list) if param_list else 'void'
        
        # Emit function signature with type checking macro
        self.code.append(f'KS_FUNC({c_ret_type}, {func_name}, {params_str}) {{')
        self.indent_level += 1
        
        # If this is main and we have deferred inits, call the init function first
        if func_name == 'main' and hasattr(self, '_deferred_inits') and self._deferred_inits:
            self.emit_line('_ks_init_globals();')
        
        # Track if we've seen a return
        has_return = False
        
        # Transpile body
        if hasattr(body, '__iter__'):
            for stmt in body:
                if stmt.__class__.__name__ in ('ReturnStmt', 'Return'):
                    has_return = True
                self.transpile_node(stmt)
        else:
            if body.__class__.__name__ in ('ReturnStmt', 'Return'):
                has_return = True
            self.transpile_node(body)
        
        # STRICT: Ensure all code paths return
        if not has_return:
            if return_type == 'void':
                self.emit_line('return;')
            else:
                self.emit_line('/* STRICT ERROR: Missing return statement */')
                self.emit_line('KS_UNREACHABLE();')
        
        self.indent_level -= 1
        self.code.append('}')
        self.code.append('')
    
    def transpile_node(self, node):
        """Transpile a single AST node"""
        if node is None:
            return
        
        node_type = node.__class__.__name__ if hasattr(node, '__class__') else str(type(node))
        
        # Enum definition
        if node_type in ('EnumDef', 'Enum_', 'Enum'):
            self.transpile_enum(node)
        
        # Function definition
        elif node_type in ('FunctionDef', 'Function'):
            self.transpile_function(node)
        
        # Return statement with STRICT type checking
        elif node_type in ('ReturnStmt', 'Return'):
            value = getattr(node, 'value', None)
            if value:
                expr = self.transpile_expression(value)
                # Use KS_RETURN macro for strict type checking
                self.emit_line(f'return {expr}; /* STRICT: Type checked */')
            else:
                self.emit_line('return;')
        
        # Variable declaration with type
        elif node_type in ('LetDecl', 'VarDecl'):
            name = getattr(node, 'name', 'var')
            value = getattr(node, 'value', None)
            var_type = getattr(node, 'var_type', None) or getattr(node, 'type_hint', None)
            
            # Check if value is a borrow expression
            is_borrow = False
            if value and hasattr(value, '__class__') and value.__class__.__name__ == 'UnaryOp':
                op = getattr(value, 'operator', None) or getattr(node, 'op', None)
                if op == 'borrow':
                    is_borrow = True
            
            # Infer type from value if not explicitly specified
            if var_type:
                c_type = self.get_typed_c_type(var_type)
            else:
                c_type = self._infer_type_from_value(value)
            
            # Special handling for arrays
            if value and hasattr(value, '__class__') and value.__class__.__name__ in ('ArrayLiteral', 'ListLiteral'):
                elements = getattr(value, 'elements', [])
                if elements:
                    # Infer element type from first element
                    elem_type = self._infer_type_from_value(elements[0])
                    c_type = f'{elem_type}[]'
                else:
                    c_type = 'long long[]'
            
            # Track variable type for later inference
            self.var_types[name] = c_type
            
            # If it's a borrow, make it a pointer type
            if is_borrow and not c_type.endswith('*'):
                c_type = c_type + '*'
            
            # Check if we're at global scope
            at_global_scope = (self.indent_level == 0)
            
            if value:
                expr = self.transpile_expression(value)
                
                # At global scope, check if initializer is constant
                if at_global_scope and self._is_non_constant_expr(value):
                    # Declare without initializer, add to deferred init list
                    self.emit_line(f'{c_type} {name};')
                    if not hasattr(self, '_deferred_inits'):
                        self._deferred_inits = []
                    self._deferred_inits.append((name, expr))
                else:
                    self.emit_line(f'{c_type} {name} = {expr};')
            else:
                self.emit_line(f'{c_type} {name};')
        
        # Function call statement (like print)
        elif node_type == 'FunctionCall':
            func = getattr(node, 'func', None)
            args = getattr(node, 'args', [])
            
            func_name = func.name if hasattr(func, 'name') else str(func)
            arg_strs = [self.transpile_expression(arg) for arg in args]
            
            # Handle print specially
            if func_name == 'print':
                for arg_str in arg_strs:
                    self.emit_line(f'printf("%s\\n", _ks_str_int({arg_str}));')
            else:
                self.emit_line(f'{func_name}({", ".join(arg_strs)});')
        
        # Other nodes - delegate to base class
        else:
            # Try base class method
            if hasattr(super(), 'transpile_node'):
                super().transpile_node(node)
    
    def transpile_enum(self, enum):
        """Transpile enum definition to C"""
        name = getattr(enum, 'name', 'UnknownEnum')
        variants = getattr(enum, 'variants', [])
        
        self.emit_line(f'typedef enum {{')
        self.indent_level += 1
        
        for i, variant in enumerate(variants):
            comma = ',' if i < len(variants) - 1 else ''
            
            # Handle tuple format (name, value) from parser
            if isinstance(variant, tuple):
                var_name, value = variant
                if value is not None:
                    self.emit_line(f'{name}_{var_name} = {value}{comma}')
                else:
                    self.emit_line(f'{name}_{var_name}{comma}')
            # Handle string
            elif isinstance(variant, str):
                self.emit_line(f'{name}_{variant}{comma}')
            # Handle object with name/value
            elif hasattr(variant, 'name'):
                var_name = variant.name
                value = getattr(variant, 'value', None)
                if value is not None:
                    self.emit_line(f'{name}_{var_name} = {value}{comma}')
                else:
                    self.emit_line(f'{name}_{var_name}{comma}')
        
        self.indent_level -= 1
        self.emit_line(f'}} {name};')
        self.emit_line('')
    
    def transpile_expression(self, node) -> str:
        """Transpile expression to C"""
        if node is None:
            return '0'
        
        node_type = node.__class__.__name__ if hasattr(node, '__class__') else str(type(node))
        
        # Literal
        if node_type == 'Literal':
            value = getattr(node, 'value', 0)
            if isinstance(value, str):
                return f'"{value}"'
            return str(value)
        
        # Identifier
        elif node_type == 'Identifier':
            return getattr(node, 'name', 'unknown')
        
        # Binary operation
        elif node_type in ('BinaryOp', 'BinOp'):
            op = getattr(node, 'op', '+')
            
            # Check for string concatenation
            if op == '+':
                left_node = getattr(node, 'left', None)
                right_node = getattr(node, 'right', None)
                left_type = self._infer_type_from_value(left_node)
                right_type = self._infer_type_from_value(right_node)
                
                if left_type == 'char*' or right_type == 'char*':
                    # String concatenation
                    left = self.transpile_expression(left_node)
                    right = self.transpile_expression(right_node)
                    return f'_ks_concat({left}, {right})'
            
            # Regular binary operation
            left = self.transpile_expression(getattr(node, 'left', None))
            right = self.transpile_expression(getattr(node, 'right', None))
            return f'({left} {op} {right})'
        
        # Unary operation (including borrow and move)
        elif node_type == 'UnaryOp':
            operand = self.transpile_expression(getattr(node, 'operand', None) or getattr(node, 'expr', None))
            op = getattr(node, 'operator', None) or getattr(node, 'op', '!')
            
            if op == 'not':
                op = '!'
            elif op == 'borrow':
                # borrow x -> &x (address-of)
                return f'(&{operand})'
            elif op == 'move':
                # move x -> x (just the value, ownership semantics handled by borrow checker)
                return operand
            
            return f'{op}{operand}'
        
        # Function call
        elif node_type == 'FunctionCall':
            func = getattr(node, 'func', None)
            args = getattr(node, 'args', [])
            
            func_name = func.name if hasattr(func, 'name') else str(func)
            arg_strs = [self.transpile_expression(arg) for arg in args]
            return f'{func_name}({", ".join(arg_strs)})'
        
        # Dict literal
        elif node_type == 'DictLiteral':
            pairs = getattr(node, 'pairs', [])
            if not pairs:
                return '_ks_dict_new()'
            # Use helper for up to 2 pairs
            if len(pairs) <= 2:
                args = []
                for key_node, val_node in pairs:
                    key = self.transpile_expression(key_node)
                    val = self.transpile_expression(val_node)
                    key_is_str = isinstance(getattr(key_node, 'value', None), str)
                    args.append(f'{key}, {val}, {1 if key_is_str else 0}')
                # Pad to 6 args (function expects k1,v1,s1,k2,v2,s2)
                if len(pairs) == 1:
                    args.append('NULL, 0, 0')
                return f'_ks_dict_create({", ".join(args)})'
            # For more pairs, use temp variable
            temp_var = f'_tmp_dict_{self.temp_counter}'
            self.temp_counter += 1
            parts = [f'{temp_var} = _ks_dict_new()']
            for key_node, val_node in pairs:
                key = self.transpile_expression(key_node)
                val = self.transpile_expression(val_node)
                key_is_str = isinstance(getattr(key_node, 'value', None), str)
                parts.append(f'_ks_dict_set({temp_var}, {key}, {val}, {1 if key_is_str else 0})')
            return f'({", ".join(parts)}, {temp_var})'
        
        # Array/List literal
        elif node_type in ('ArrayLiteral', 'ListLiteral'):
            elements = getattr(node, 'elements', [])
            elem_strs = [self.transpile_expression(e) for e in elements]
            return f"{{{', '.join(elem_strs)}}}"
        
        # Index access (array or dict)
        elif node_type in ('Index', 'IndexAccess'):
            obj_node = getattr(node, 'object', None) or getattr(node, 'array', None)
            obj = self.transpile_expression(obj_node)
            index = self.transpile_expression(getattr(node, 'index', None))
            
            # Determine if it's an array or dict by checking the object's type
            obj_name = getattr(obj_node, 'name', None) if hasattr(obj_node, 'name') else None
            if obj_name and obj_name in self.var_types:
                var_type = self.var_types[obj_name]
                # If it's an array type (contains []), use direct indexing
                if '[' in var_type or var_type.endswith('*'):
                    return f'{obj}[{index}]'
            
            # Check if the object is an identifier that was initialized with an array
            if obj_name:
                # Default to array indexing for now (safer assumption)
                return f'{obj}[{index}]'
            
            # Otherwise assume dict access
            return f'_ks_dict_get_simple({obj}, {index})'
        
        return '0'
    
    def emit_line(self, line: str):
        """Emit indented line"""
        indent = '    ' * self.indent_level
        self.code.append(f'{indent}{line}')


def main():
    """Test the typed transpiler"""
    if len(sys.argv) < 2:
        print("Usage: python3 c_transpiler_typed.py input.ks")
        return
    
    input_file = sys.argv[1]
    
    # Parse KentScript
    from ks_core import Lexer, Parser
    
    with open(input_file, 'r') as f:
        source = f.read()
    
    lexer = Lexer(source)
    tokens = lexer.tokenize()
    parser = Parser(tokens, source)
    ast = parser.parse()
    
    # Transpile with type system
    transpiler = TypedCTranspiler()
    c_code = transpiler.transpile(ast)
    
    # Write output
    output_file = input_file.replace('.ks', '_typed.c')
    with open(output_file, 'w') as f:
        f.write(c_code)
    
    print(f"✓ Generated typed C code: {output_file}")
    print(f"  Compile with: gcc {output_file} -o program -I.")
    print(f"  Type checking enforced at compile-time!")


if __name__ == '__main__':
    main()
