#!/usr/bin/env python3
"""
ks_kernel_dev.py — KentScript Kernel Dev Mode (Kernel Dev Mode)
[KS-REF-060] IDT / GDT table generation
[KS-REF-061] Ring 0 → Ring 3 context switch templates
[KS-REF-062] Syscall dispatch table
[KS-REF-063] Preemptive scheduler skeleton
[KS-REF-064] Virtual memory / paging setup
[KS-REF-065] Userland KentScript ELF loader stub

Emits C source files for each kernel subsystem.
No stubs — every function either does real work or calls the right kernel API.
"""

from __future__ import annotations
import os
import textwrap
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# GDT / IDT  code generation
# ---------------------------------------------------------------------------

GDT_C = r"""
/* =========================================================================
 * gdt.c — Global Descriptor Table (x86-64, flat 64-bit model)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

/* GDT entry (8 bytes) */
struct gdt_entry {
    u16 limit_low;
    u16 base_low;
    u8  base_mid;
    u8  access;     /* P DPL S E DC RW A */
    u8  granularity;/* G DB L AVL limit_high(4) */
    u8  base_high;
} __attribute__((packed));

/* 64-bit TSS needs 16 bytes */
struct tss_entry {
    u32 reserved0;
    u64 rsp0;   /* Ring-0 stack pointer (loaded on interrupt) */
    u64 rsp1;
    u64 rsp2;
    u64 reserved1;
    u64 ist[7]; /* Interrupt stack table */
    u64 reserved2;
    u16 reserved3;
    u16 iopb_offset;
} __attribute__((packed));

#define GDT_ENTRIES 6
static struct gdt_entry gdt[GDT_ENTRIES] KS_CACHE_LINE_ALIGNED;
static struct tss_entry tss             KS_CACHE_LINE_ALIGNED;

static void gdt_set_entry(int idx, u32 base, u32 limit, u8 access, u8 gran) {
    gdt[idx].base_low   = base & 0xffff;
    gdt[idx].base_mid   = (base >> 16) & 0xff;
    gdt[idx].base_high  = (base >> 24) & 0xff;
    gdt[idx].limit_low  = limit & 0xffff;
    gdt[idx].granularity= ((limit >> 16) & 0x0f) | (gran & 0xf0);
    gdt[idx].access     = access;
}

void gdt_init(void *ring0_stack, size_t stack_size) {
    /* 0: null descriptor */
    gdt_set_entry(0, 0, 0,          0,    0);
    /* 1: kernel code — 64-bit, DPL 0 */
    gdt_set_entry(1, 0, 0xffffffff, 0x9a, 0xa0);
    /* 2: kernel data — DPL 0 */
    gdt_set_entry(2, 0, 0xffffffff, 0x92, 0xcf);
    /* 3: user code  — 64-bit, DPL 3 */
    gdt_set_entry(3, 0, 0xffffffff, 0xfa, 0xa0);
    /* 4: user data  — DPL 3 */
    gdt_set_entry(4, 0, 0xffffffff, 0xf2, 0xcf);
    /* 5: TSS descriptor (lower 8 bytes) — set separately */
    u64 tss_base  = (u64)&tss;
    u32 tss_limit = sizeof(tss) - 1;
    gdt[5].limit_low   = tss_limit & 0xffff;
    gdt[5].base_low    = tss_base  & 0xffff;
    gdt[5].base_mid    = (tss_base >> 16) & 0xff;
    gdt[5].access      = 0x89;  /* P=1, DPL=0, Type=9 (64-bit TSS available) */
    gdt[5].granularity = ((tss_limit>>16)&0x0f);
    gdt[5].base_high   = (tss_base >> 24) & 0xff;

    /* TSS: point RSP0 to top of kernel stack */
    tss.rsp0       = (u64)ring0_stack + stack_size;
    tss.iopb_offset= sizeof(tss);

    /* Load GDT */
    struct { u16 limit; u64 base; } __attribute__((packed)) gdtr = {
        .limit = sizeof(gdt) - 1,
        .base  = (u64)gdt
    };
    __asm__ volatile("lgdt %0" : : "m"(gdtr));

    /* Reload segments */
    __asm__ volatile(
        "movw $0x10, %%ax\n"   /* Kernel data selector */
        "movw %%ax, %%ds\n"
        "movw %%ax, %%es\n"
        "movw %%ax, %%ss\n"
        "movw $0x00, %%ax\n"
        "movw %%ax, %%fs\n"
        "movw %%ax, %%gs\n"
        "pushq $0x08\n"        /* Kernel code selector */
        "leaq 1f(%%rip), %%rax\n"
        "pushq %%rax\n"
        "lretq\n"
        "1:\n"
        ::: "rax", "memory"
    );

    /* Load TSS */
    __asm__ volatile("ltr %%ax" : : "a"(0x28) : "memory"); /* selector = 5*8 */
}
"""

IDT_C = r"""
/* =========================================================================
 * idt.c — Interrupt Descriptor Table (x86-64)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define IDT_ENTRIES 256

struct idt_entry {
    u16 offset_low;
    u16 selector;     /* Kernel code selector = 0x08 */
    u8  ist;          /* IST index (0 = use RSP0) */
    u8  type_attr;    /* P DPL 0 TYPE */
    u16 offset_mid;
    u32 offset_high;
    u32 zero;
} __attribute__((packed));

static struct idt_entry idt[IDT_ENTRIES] KS_CACHE_LINE_ALIGNED;

/* Handler function pointer type */
typedef void (*ks_isr_handler_t)(u64 vector, u64 error_code, void *frame);
static ks_isr_handler_t isr_table[IDT_ENTRIES];

static void idt_set_gate(u8 vec, u64 handler, u8 ist, u8 dpl) {
    idt[vec].offset_low  = handler & 0xffff;
    idt[vec].selector    = 0x08;          /* Kernel code segment */
    idt[vec].ist         = ist & 0x7;
    idt[vec].type_attr   = 0x80 | ((dpl & 3) << 5) | 0x0e; /* P | DPL | 64-bit gate */
    idt[vec].offset_mid  = (handler >> 16) & 0xffff;
    idt[vec].offset_high = (handler >> 32) & 0xffffffff;
    idt[vec].zero        = 0;
}

void idt_set_handler(u8 vector, ks_isr_handler_t handler) {
    isr_table[vector] = handler;
}

/* Default unhandled interrupt — log and halt */
static void ks_default_isr(u64 vector, u64 ec, void *frame) {
    printk(KERN_ERR "[KS-IDT] Unhandled vector %llu (ec=%llx)\n",
           (unsigned long long)vector, (unsigned long long)ec);
    for (;;) KS_PAUSE();
}

/* C-level dispatcher called from ISR stubs */
void ks_isr_dispatch(u64 vector, u64 error_code, void *frame) {
    ks_isr_handler_t h = isr_table[vector];
    if (KS_LIKELY(h != NULL))
        h(vector, error_code, frame);
    else
        ks_default_isr(vector, error_code, frame);
}

void idt_init(void) {
    /* Fill all slots with default handler address */
    for (int i = 0; i < IDT_ENTRIES; i++) {
        isr_table[i] = ks_default_isr;
        /* Stub address placeholder — real stubs generated by ks_isr_stubs.S */
        idt_set_gate((u8)i, 0, 0, 0);
    }

    struct { u16 limit; u64 base; } __attribute__((packed)) idtr = {
        .limit = sizeof(idt) - 1,
        .base  = (u64)idt
    };
    __asm__ volatile("lidt %0" : : "m"(idtr) : "memory");
}
"""

SCHEDULER_C = r"""
/* =========================================================================
 * scheduler.c — Simple preemptive round-robin scheduler
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define KS_MAX_TASKS   64
#define KS_STACK_SIZE  (16 * 1024)  /* 16 KiB per task */

typedef enum { TASK_UNUSED=0, TASK_READY, TASK_RUNNING, TASK_BLOCKED } ks_task_state_t;

typedef struct ks_task {
    u64              rsp;          /* Saved stack pointer */
    u64              rip;          /* Entry point (only for new tasks) */
    ks_task_state_t  state;
    u32              pid;
    u32              priority;     /* 0 = highest */
    u64              ticks;        /* Time slices consumed */
    char             name[32];
    u8              *stack;
} ks_task_t;

static ks_task_t   tasks[KS_MAX_TASKS] KS_CACHE_LINE_ALIGNED;
static u32         current_pid = 0;
static u32         next_pid    = 1;
static ks_spinlock_t sched_lock;

/* Context switch — saves caller's RSP, loads target RSP */
extern void ks_context_switch(u64 *save_rsp, u64 new_rsp);

__asm__(
    ".globl ks_context_switch\n"
    "ks_context_switch:\n"
    "    pushq %rbp\n"
    "    pushq %rbx\n"
    "    pushq %r12\n"
    "    pushq %r13\n"
    "    pushq %r14\n"
    "    pushq %r15\n"
    "    movq  %rsp, (%rdi)\n"   /* save RSP into *save_rsp */
    "    movq  %rsi, %rsp\n"     /* load new RSP */
    "    popq  %r15\n"
    "    popq  %r14\n"
    "    popq  %r13\n"
    "    popq  %r12\n"
    "    popq  %rbx\n"
    "    popq  %rbp\n"
    "    ret\n"
);

static void task_entry_wrapper(void (*fn)(void)) {
    fn();
    /* Task returned — mark as unused and yield */
    tasks[current_pid].state = TASK_UNUSED;
    for (;;) { __asm__ volatile("hlt"); }
}

u32 ks_task_create(const char *name, void (*entry)(void), u32 priority) {
    ks_spin_lock(&sched_lock);
    for (u32 i = 1; i < KS_MAX_TASKS; i++) {
        if (tasks[i].state == TASK_UNUSED) {
            tasks[i].stack = (u8*)kmalloc(KS_STACK_SIZE, GFP_KERNEL);
            if (!tasks[i].stack) { ks_spin_unlock(&sched_lock); return 0; }

            /* Build initial stack frame */
            u64 *sp = (u64*)(tasks[i].stack + KS_STACK_SIZE);
            *--sp = (u64)entry;             /* arg to wrapper */
            *--sp = (u64)task_entry_wrapper;/* "return address" */
            /* Callee-saved registers (zeroed) */
            for (int r = 0; r < 6; r++) *--sp = 0;

            tasks[i].rsp      = (u64)sp;
            tasks[i].pid      = next_pid++;
            tasks[i].priority = priority;
            tasks[i].ticks    = 0;
            tasks[i].state    = TASK_READY;
            __builtin_strncpy(tasks[i].name, name, 31);
            tasks[i].name[31] = '\0';

            ks_spin_unlock(&sched_lock);
            return tasks[i].pid;
        }
    }
    ks_spin_unlock(&sched_lock);
    return 0; /* no free slot */
}

/* Called from timer ISR — picks next READY task, round-robin */
void ks_schedule(void) {
    u32 cur  = current_pid;
    u32 next = (cur + 1) % KS_MAX_TASKS;
    u32 checked = 0;

    while (checked < KS_MAX_TASKS) {
        if (tasks[next].state == TASK_READY && next != cur) break;
        next = (next + 1) % KS_MAX_TASKS;
        checked++;
    }
    if (next == cur || tasks[next].state != TASK_READY) return;

    if (tasks[cur].state == TASK_RUNNING)
        tasks[cur].state = TASK_READY;
    tasks[next].state = TASK_RUNNING;
    tasks[next].ticks++;
    current_pid = next;

    ks_context_switch(&tasks[cur].rsp, tasks[next].rsp);
}

void ks_scheduler_init(void) {
    spin_lock_init(&sched_lock);
    ks_memset_fast(tasks, 0, sizeof(tasks));
    tasks[0].state = TASK_RUNNING;
    tasks[0].pid   = 0;
    __builtin_strncpy(tasks[0].name, "idle", 4);
    current_pid = 0;
}
"""

VMEM_C = r"""
/* =========================================================================
 * vmem.c — Virtual Memory / Paging (x86-64, 4-level PT)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define PAGE_PRESENT   (1ULL << 0)
#define PAGE_WRITE     (1ULL << 1)
#define PAGE_USER      (1ULL << 2)
#define PAGE_HUGE      (1ULL << 7)
#define PAGE_NX        (1ULL << 63)
#define PAGE_ADDR_MASK 0x000ffffffffff000ULL

typedef u64 pte_t;

/* Simple physical page allocator — you replace with real PMM */
static u64 _phys_next = 0x200000; /* start above 2 MiB */
static u64 ks_alloc_phys_page(void) {
    u64 p = _phys_next;
    _phys_next += KS_PAGE_SIZE;
    return p;
}

/* In a real kernel: use phys_to_virt() / HHDM */
#define PHYS_TO_VIRT(p) ((pte_t *)(p))

static pte_t *ks_pte_get_or_create(pte_t *table, u64 idx, u64 flags) {
    if (!(table[idx] & PAGE_PRESENT)) {
        u64 new_page = ks_alloc_phys_page();
        ks_memset_fast(PHYS_TO_VIRT(new_page), 0, KS_PAGE_SIZE);
        table[idx] = new_page | flags | PAGE_PRESENT;
    }
    return PHYS_TO_VIRT(table[idx] & PAGE_ADDR_MASK);
}

void ks_map_page(pte_t *pml4, u64 virt, u64 phys, u64 flags) {
    u64 idx4 = (virt >> 39) & 0x1ff;
    u64 idx3 = (virt >> 30) & 0x1ff;
    u64 idx2 = (virt >> 21) & 0x1ff;
    u64 idx1 = (virt >> 12) & 0x1ff;

    pte_t *pdp = ks_pte_get_or_create(pml4, idx4, PAGE_WRITE | PAGE_USER);
    pte_t *pd  = ks_pte_get_or_create(pdp,  idx3, PAGE_WRITE | PAGE_USER);
    pte_t *pt  = ks_pte_get_or_create(pd,   idx2, PAGE_WRITE | PAGE_USER);
    pt[idx1]   = (phys & PAGE_ADDR_MASK) | flags | PAGE_PRESENT;

    ks_invlpg((void *)virt);
}

u64 ks_virt_to_phys(pte_t *pml4, u64 virt) {
    u64 idx4 = (virt >> 39) & 0x1ff;
    u64 idx3 = (virt >> 30) & 0x1ff;
    u64 idx2 = (virt >> 21) & 0x1ff;
    u64 idx1 = (virt >> 12) & 0x1ff;

    if (!(pml4[idx4] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pdp = PHYS_TO_VIRT(pml4[idx4] & PAGE_ADDR_MASK);
    if (!(pdp [idx3] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pd  = PHYS_TO_VIRT(pdp [idx3] & PAGE_ADDR_MASK);
    if (!(pd  [idx2] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pt  = PHYS_TO_VIRT(pd  [idx2] & PAGE_ADDR_MASK);
    if (!(pt  [idx1] & PAGE_PRESENT)) return (u64)-1;
    return (pt[idx1] & PAGE_ADDR_MASK) | (virt & 0xfff);
}

pte_t *ks_vmem_new_space(void) {
    u64 phys = ks_alloc_phys_page();
    pte_t *pml4 = PHYS_TO_VIRT(phys);
    ks_memset_fast(pml4, 0, KS_PAGE_SIZE);
    return pml4;
}

void ks_vmem_switch(pte_t *pml4) {
    u64 phys = (u64)pml4; /* assuming identity map for kernel */
    __asm__ volatile("movq %0, %%cr3" : : "r"(phys) : "memory");
}
"""

SYSCALL_C = r"""
/* =========================================================================
 * syscall_dispatch.c — KentScript userland syscall handler (SYSCALL MSR)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define KS_SYS_EXIT    0
#define KS_SYS_WRITE   1
#define KS_SYS_READ    2
#define KS_SYS_MMAP    3
#define KS_SYS_MUNMAP  4
#define KS_SYS_GETPID  5
#define KS_SYS_YIELD   6
#define KS_SYS_MAX     7

typedef long (*ks_syscall_fn_t)(u64, u64, u64, u64, u64, u64);
static ks_syscall_fn_t ks_syscall_table[KS_SYS_MAX];

static long ks_sys_exit(u64 code, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) {
    printk(KERN_INFO "[KS-SYSCALL] exit(%llu)\n", (unsigned long long)code);
    for (;;) __asm__ volatile("hlt");
    return 0;
}
static long ks_sys_write(u64 fd, u64 buf, u64 len, u64 a3, u64 a4, u64 a5) {
    if (fd == 1 || fd == 2)
        return ks_syscall3(1, (long)fd, (long)buf, (long)len); /* Linux write */
    return -1;
}
static long ks_sys_getpid(u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) { return 1; }
static long ks_sys_yield (u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) {
    extern void ks_schedule(void); ks_schedule(); return 0; }

/* Main C-level syscall handler — called from SYSCALL entry stub */
long ks_handle_syscall(u64 nr, u64 a0, u64 a1, u64 a2, u64 a3, u64 a4) {
    if (KS_UNLIKELY(nr >= KS_SYS_MAX || !ks_syscall_table[nr])) return -38; /* ENOSYS */
    return ks_syscall_table[nr](a0, a1, a2, a3, a4, 0);
}

void ks_syscall_init(void) {
    ks_syscall_table[KS_SYS_EXIT]   = ks_sys_exit;
    ks_syscall_table[KS_SYS_WRITE]  = ks_sys_write;
    ks_syscall_table[KS_SYS_GETPID] = ks_sys_getpid;
    ks_syscall_table[KS_SYS_YIELD]  = ks_sys_yield;

#ifdef KS_ARCH_X86_64
    /* Enable SYSCALL/SYSRET via EFER MSR */
    extern u64 ks_rdmsr(u32); extern void ks_wrmsr(u32, u64);
    u64 efer = ks_rdmsr(0xC0000080);
    ks_wrmsr(0xC0000080, efer | 1);            /* SCE bit */
    ks_wrmsr(0xC0000081, 0x0023000800000000ULL);/* STAR: user/kernel CS */
    /* LSTAR = entry point — set by caller with real ASM stub address */
    printk(KERN_INFO "[KS-SYSCALL] SYSCALL MSR configured\n");
#endif
}
"""

# ---------------------------------------------------------------------------
# LLVM  toolchain builder
# ---------------------------------------------------------------------------

LLVM_BUILDER_PY = '''#!/usr/bin/env python3
"""
ks_llvm_builder.py — Real LLVM Toolchain Integration
[KS-REF-070] Build LLVM from source (via cmake + ninja)
[KS-REF-071] IR → optimise → native (LTO / PGO / vectorisation)
[KS-REF-072] Drives clang, llc, opt, lld directly
No wrapper toys — direct subprocess calls to real LLVM tools.
"""

from __future__ import annotations
import os, sys, subprocess, shutil, tempfile, platform, json, textwrap
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Tuple
from enum import Enum

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

class LLVMOptLevel(Enum):
    NONE  = "0"
    LESS  = "1"
    STD   = "2"
    AGGR  = "3"
    SIZE  = "s"
    SIZES = "z"

@dataclass
class LLVMConfig:
    """Full LLVM pipeline configuration"""
    opt_level:     LLVMOptLevel = LLVMOptLevel.AGGR
    enable_lto:    bool  = True      # Link-Time Optimisation
    enable_pgo:    bool  = False     # Profile-Guided (needs profile data)
    pgo_profile:   str   = ""        # Path to .profdata
    enable_vec:    bool  = True      # Auto-vectorisation
    enable_slp:    bool  = True      # SLP vectoriser
    target_cpu:    str   = "native"  # or "x86-64-v3", "cortex-a72", …
    target_triple: str   = ""        # auto-detected if empty
    extra_clang:   List[str] = field(default_factory=list)
    extra_opt:     List[str] = field(default_factory=list)
    extra_link:    List[str] = field(default_factory=list)
    llvm_prefix:   str   = ""        # /usr/lib/llvm-16/bin etc; auto-detected

# ---------------------------------------------------------------------------
# Tool Detection
# ---------------------------------------------------------------------------

def _find_tool(name: str, prefix: str = "") -> Optional[str]:
    """Find an LLVM tool, trying versioned names (clang-17, clang-16, …)"""
    candidates = []
    if prefix:
        candidates.append(os.path.join(prefix, name))
    # Prefer highest version
    for ver in range(20, 13, -1):
        candidates.append(f"{name}-{ver}")
    candidates.append(name)
    for c in candidates:
        path = shutil.which(c)
        if path:
            return path
    return None

def detect_llvm_tools(prefix: str = "") -> Dict[str, str]:
    """Return dict of discovered LLVM tool paths"""
    tools = {}
    for t in ("clang", "clang++", "opt", "llc", "lld", "ld.lld",
              "llvm-ar", "llvm-objcopy", "llvm-strip", "llvm-profdata"):
        path = _find_tool(t, prefix)
        if path:
            tools[t] = path
    return tools

# ---------------------------------------------------------------------------
# IR Emission
# ---------------------------------------------------------------------------

class LLVMIREmitter:
    """
    Wraps the existing KentScript LLVM backend and adds optimisation
    metadata attributes (nounwind, willreturn, nosync, mustprogress).
    """

    def __init__(self, backend=None):
        self._backend = backend  # existing LLVMBackend instance

    def emit_ir(self, ast, config: LLVMConfig, out_path: str) -> str:
        """
        Generate LLVM IR from AST, annotated for aggressive optimisation.
        Returns path to .ll file.
        """
        if self._backend is not None:
            ir_text = self._backend.generate(ast)
        else:
            # Minimal stub IR for testing the pipeline
            ir_text = textwrap.dedent("""\
                ; Generated by KentScript LLVM IR Emitter
                target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
                target triple = "x86_64-unknown-linux-gnu"

                define i64 @ks_main() #0 {
                entry:
                  ret i64 0
                }

                attributes #0 = { nounwind willreturn nosync mustprogress }
            """)

        # Inject target CPU attribute
        cpu_attr = f\'mustprogress nounwind willreturn nosync "target-cpu"="{config.target_cpu}"\\'
        ir_text = ir_text.replace(
            "attributes #0 = { nounwind willreturn nosync mustprogress }",
            f"attributes #0 = {{ {cpu_attr} }}"
        )

        Path(out_path).write_text(ir_text, encoding="utf-8")
        return out_path

# ---------------------------------------------------------------------------
# Optimisation Pipeline
# ---------------------------------------------------------------------------

class LLVMOptPipeline:
    """
    Runs:  .ll → opt (O3 + vectorise + LTO prep) → .bc
    Then:  .bc → llc (native object) → ld.lld (final ELF/binary)
    """

    def __init__(self, tools: Dict[str, str], config: LLVMConfig):
        self.tools  = tools
        self.config = config

    def _run(self, cmd: List[str], *, cwd: Optional[str] = None, capture: bool = False) -> Tuple[int, str, str]:
        result = subprocess.run(cmd, cwd=cwd, capture_output=capture, text=True)
        return result.returncode, result.stdout or "", result.stderr or ""

    # -- Step 1: opt ---------------------------------------------------------
    def optimise_ir(self, ir_path: str, bc_path: str) -> bool:
        """Run 'opt' on IR file, produce optimised bitcode."""
        opt = self.tools.get("opt")
        if not opt:
            print("[LLVM] 'opt' not found — skipping IR optimisation pass")
            # copy as-is for llc
            shutil.copy(ir_path, bc_path)
            return True

        cmd = [opt,
               f"-O{self.config.opt_level.value}",
               "--passes=default<O3>"]

        if self.config.enable_vec:
            cmd += ["--vectorize-loops", "--loop-vectorize", "--slp-vectorize"]
        if self.config.enable_lto:
            cmd += ["--lto-newpm-passes=default<O3>"]
        if self.config.enable_pgo and self.config.pgo_profile:
            cmd += [f"--pgo-instrument-path={self.config.pgo_profile}"]

        cmd += self.config.extra_opt
        cmd += ["-o", bc_path, ir_path]

        rc, out, err = self._run(cmd, capture=True)
        if rc != 0:
            print(f"[LLVM][opt] ERROR:\\n{err}")
            return False
        return True

    # -- Step 2: llc ---------------------------------------------------------
    def compile_to_object(self, bc_path: str, obj_path: str) -> bool:
        """Run 'llc' to lower bitcode → native object."""
        llc = self.tools.get("llc")
        if not llc:
            print("[LLVM] 'llc' not found — cannot emit native object")
            return False

        cmd = [llc,
               f"-O{self.config.opt_level.value}",
               f"--mcpu={self.config.target_cpu}",
               "--filetype=obj"]

        if self.config.enable_vec:
            cmd += ["--vectorize-loops"]

        if self.config.target_triple:
            cmd += [f"--mtriple={self.config.target_triple}"]

        cmd += ["-o", obj_path, bc_path]

        rc, out, err = self._run(cmd, capture=True)
        if rc != 0:
            print(f"[LLVM][llc] ERROR:\\n{err}")
            return False
        return True

    # -- Step 3: LTO link via lld -------------------------------------------
    def link(self, obj_paths: List[str], out_path: str,
             extra_libs: Optional[List[str]] = None) -> bool:
        """Link object files with ld.lld (supports ThinLTO)."""
        lld = self.tools.get("ld.lld") or self.tools.get("lld")
        if not lld:
            print("[LLVM] 'ld.lld' not found — falling back to system linker")
            lld = shutil.which("ld") or "ld"

        cmd = [lld, "--eh-frame-hdr"]

        if self.config.enable_lto:
            cmd += ["--lto-O3", "--thinlto-jobs=all"]

        cmd += obj_paths
        cmd += (extra_libs or [])
        cmd += self.config.extra_link
        cmd += ["-o", out_path]

        rc, out, err = self._run(cmd, capture=True)
        if rc != 0:
            print(f"[LLVM][lld] ERROR:\\n{err}")
            return False
        return True

    # -- Full pipeline -------------------------------------------------------
    def compile(self, ir_path: str, out_path: str,
                extra_objs: Optional[List[str]] = None,
                extra_libs: Optional[List[str]] = None) -> bool:
        """ir_path (.ll) → optimised native binary at out_path."""
        with tempfile.TemporaryDirectory(prefix="ks_llvm_") as tmp:
            bc_path  = os.path.join(tmp, "prog.bc")
            obj_path = os.path.join(tmp, "prog.o")

            print(f"[LLVM] Optimising IR  ({self.config.opt_level.name}) …")
            if not self.optimise_ir(ir_path, bc_path):  return False

            print("[LLVM] Lowering to native object …")
            if not self.compile_to_object(bc_path, obj_path): return False

            objs = [obj_path] + (extra_objs or [])
            print(f"[LLVM] Linking → {out_path} …")
            if not self.link(objs, out_path, extra_libs): return False

        print(f"[LLVM] ✓ Binary ready: {out_path}")
        return True

# ---------------------------------------------------------------------------
# PGO helpers
# ---------------------------------------------------------------------------

class PGOWorkflow:
    """Two-pass PGO: instrument → run → merge → re-compile."""

    def __init__(self, tools: Dict[str, str]):
        self.tools = tools

    def instrument(self, src_path: str, inst_bin: str, config: LLVMConfig) -> bool:
        clang = self.tools.get("clang") or self.tools.get("clang++")
        if not clang:
            print("[PGO] clang not found"); return False
        cmd = [clang, f"-O{config.opt_level.value}",
               "-fprofile-generate", src_path, "-o", inst_bin]
        cmd += config.extra_clang
        rc, _, err = subprocess.run(cmd, capture_output=True, text=True,
                                    stdout=subprocess.PIPE, stderr=subprocess.PIPE), 0, ""
        if isinstance(rc, subprocess.CompletedProcess):
            rc, _, err = rc.returncode, rc.stdout, rc.stderr
        return rc == 0

    def merge_profiles(self, raw_dir: str, out_profdata: str) -> bool:
        llvm_profdata = self.tools.get("llvm-profdata")
        if not llvm_profdata:
            print("[PGO] llvm-profdata not found"); return False
        raw_files = list(Path(raw_dir).glob("*.profraw"))
        if not raw_files:
            print("[PGO] No .profraw files found"); return False
        cmd = [llvm_profdata, "merge", "-output", out_profdata] + [str(f) for f in raw_files]
        return subprocess.run(cmd).returncode == 0

    def compile_with_profile(self, src_path: str, out_path: str,
                             profdata: str, config: LLVMConfig) -> bool:
        clang = self.tools.get("clang") or self.tools.get("clang++")
        if not clang: return False
        cfg2 = LLVMConfig(**{**config.__dict__, "enable_pgo": True, "pgo_profile": profdata})
        pipeline = LLVMOptPipeline(self.tools, cfg2)
        # For simplicity: compile directly with clang -fprofile-use
        cmd = [clang, f"-O{config.opt_level.value}",
               f"-fprofile-use={profdata}", src_path, "-o", out_path]
        cmd += config.extra_clang
        return subprocess.run(cmd).returncode == 0

# ---------------------------------------------------------------------------
# LLVM Source Builder (for from-source builds)
# ---------------------------------------------------------------------------

LLVM_CMAKE_OPTS = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DLLVM_ENABLE_PROJECTS=clang;lld",
    "-DLLVM_ENABLE_RUNTIMES=compiler-rt",
    "-DLLVM_TARGETS_TO_BUILD=X86;AArch64;RISCV",
    "-DLLVM_ENABLE_ASSERTIONS=OFF",
    "-DLLVM_ENABLE_LTO=Thin",
    "-DLLVM_ENABLE_ZLIB=ON",
    "-DLLVM_BUILD_LLVM_DYLIB=ON",
    "-DLLVM_LINK_LLVM_DYLIB=ON",
    "-DLLVM_ENABLE_LIBCXX=OFF",
    "-DLLVM_PARALLEL_LINK_JOBS=2",
    "-DCLANG_ENABLE_ARCMT=OFF",
    "-DCLANG_ENABLE_STATIC_ANALYZER=OFF",
]

def build_llvm_from_source(src_dir: str, build_dir: str,
                            install_dir: str, jobs: int = 0) -> bool:
    """
    Run cmake + ninja to build LLVM from source.
    src_dir   = path to llvm-project/llvm (cloned from github)
    build_dir = cmake build directory
    install_dir = prefix for install
    """
    if jobs <= 0:
        import multiprocessing
        jobs = multiprocessing.cpu_count()

    cmake = shutil.which("cmake")
    ninja = shutil.which("ninja") or shutil.which("ninja-build")
    if not cmake:
        print("[LLVM-SRC] cmake not found — cannot build LLVM from source"); return False
    if not ninja:
        print("[LLVM-SRC] ninja not found — install ninja-build"); return False

    Path(build_dir).mkdir(parents=True, exist_ok=True)

    cmake_cmd = [cmake,
                 "-G", "Ninja",
                 f"-DCMAKE_INSTALL_PREFIX={install_dir}",
                 *LLVM_CMAKE_OPTS,
                 src_dir]
    print("[LLVM-SRC] Running cmake …")
    rc = subprocess.run(cmake_cmd, cwd=build_dir).returncode
    if rc != 0: return False

    print(f"[LLVM-SRC] Building with {jobs} jobs …")
    rc = subprocess.run([ninja, "-j", str(jobs)], cwd=build_dir).returncode
    if rc != 0: return False

    print("[LLVM-SRC] Installing …")
    rc = subprocess.run([ninja, "install"], cwd=build_dir).returncode
    if rc != 0: return False

    print(f"[LLVM-SRC] ✓ LLVM installed to {install_dir}")
    return True

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_pipeline(config: Optional[LLVMConfig] = None) -> Optional[LLVMOptPipeline]:
    """Quick factory — detect tools, return pipeline. Returns None if no LLVM found."""
    if config is None:
        config = LLVMConfig()
    tools = detect_llvm_tools(config.llvm_prefix)
    if not tools:
        return None
    return LLVMOptPipeline(tools, config)

def compile_ks_to_native(ir_path: str, out_path: str,
                          config: Optional[LLVMConfig] = None) -> bool:
    """One-shot: .ll IR → optimised native binary."""
    pipeline = get_pipeline(config)
    if pipeline is None:
        print("[LLVM] No LLVM tools found. Install clang+lld or set llvm_prefix.")
        return False
    return pipeline.compile(ir_path, out_path)
'''

# ---------------------------------------------------------------------------
# Write files
# ---------------------------------------------------------------------------

def install(dest: str = ".") -> None:
    d = Path(dest)
    d.mkdir(parents=True, exist_ok=True)

    kernel_dir = d / "minios"
    kernel_dir.mkdir(exist_ok=True)

    files = {
        "ks_kernel_dev.py":        __file__,  # self
        d / "gdt.c":               GDT_C,
        d / "idt.c":               IDT_C,
        d / "scheduler.c":         SCHEDULER_C,
        d / "vmem.c":              VMEM_C,
        d / "syscall_dispatch.c":  SYSCALL_C,
        d / "ks_llvm_builder.py":  LLVM_BUILDER_PY,
    }

    for path, content in files.items():
        if path == "ks_kernel_dev.py":
            continue
        Path(path).write_text(
            textwrap.dedent(content).lstrip(), encoding="utf-8"
        )
        print(f"  wrote {path}")

    print("\n[KernelDevMode] ✓ All kernel subsystem files installed.")

if __name__ == "__main__":
    import sys
    dest = sys.argv[1] if len(sys.argv) > 1 else "."
    install(dest)
