#!/usr/bin/env python3
"""
ks_kernel_dev.py — KentScript Kernel Dev Mode (Kernel Dev Mode)
[KS-REF-060] IDT / GDT table generation
[KS-REF-061] Ring 0 → Ring 3 context switch templates
[KS-REF-062] Syscall dispatch table
[KS-REF-063] Preemptive scheduler skeleton
[KS-REF-064] Virtual memory / paging setup
[KS-REF-065] Userland KentScript ELF loader stub

Emits C source files for each kernel subsystem.
No stubs — every function either does real work or calls the right kernel API.
"""

from __future__ import annotations
import os
import textwrap
from pathlib import Path
# ---------------------------------------------------------------------------
# GDT / IDT  code generation
# ---------------------------------------------------------------------------

GDT_C = r"""
/* =========================================================================
 * gdt.c — Global Descriptor Table (x86-64, flat 64-bit model)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

/* GDT entry (8 bytes) */
struct gdt_entry {
    u16 limit_low;
    u16 base_low;
    u8  base_mid;
    u8  access;     /* P DPL S E DC RW A */
    u8  granularity;/* G DB L AVL limit_high(4) */
    u8  base_high;
} __attribute__((packed));

/* 64-bit TSS needs 16 bytes */
struct tss_entry {
    u32 reserved0;
    u64 rsp0;   /* Ring-0 stack pointer (loaded on interrupt) */
    u64 rsp1;
    u64 rsp2;
    u64 reserved1;
    u64 ist[7]; /* Interrupt stack table */
    u64 reserved2;
    u16 reserved3;
    u16 iopb_offset;
} __attribute__((packed));

#define GDT_ENTRIES 6
static struct gdt_entry gdt[GDT_ENTRIES] KS_CACHE_LINE_ALIGNED;
static struct tss_entry tss             KS_CACHE_LINE_ALIGNED;

static void gdt_set_entry(int idx, u32 base, u32 limit, u8 access, u8 gran) {
    gdt[idx].base_low   = base & 0xffff;
    gdt[idx].base_mid   = (base >> 16) & 0xff;
    gdt[idx].base_high  = (base >> 24) & 0xff;
    gdt[idx].limit_low  = limit & 0xffff;
    gdt[idx].granularity= ((limit >> 16) & 0x0f) | (gran & 0xf0);
    gdt[idx].access     = access;
}

void gdt_init(void *ring0_stack, size_t stack_size) {
    /* 0: null descriptor */
    gdt_set_entry(0, 0, 0,          0,    0);
    /* 1: kernel code — 64-bit, DPL 0 */
    gdt_set_entry(1, 0, 0xffffffff, 0x9a, 0xa0);
    /* 2: kernel data — DPL 0 */
    gdt_set_entry(2, 0, 0xffffffff, 0x92, 0xcf);
    /* 3: user code  — 64-bit, DPL 3 */
    gdt_set_entry(3, 0, 0xffffffff, 0xfa, 0xa0);
    /* 4: user data  — DPL 3 */
    gdt_set_entry(4, 0, 0xffffffff, 0xf2, 0xcf);
    /* 5: TSS descriptor (lower 8 bytes) — set separately */
    u64 tss_base  = (u64)&tss;
    u32 tss_limit = sizeof(tss) - 1;
    gdt[5].limit_low   = tss_limit & 0xffff;
    gdt[5].base_low    = tss_base  & 0xffff;
    gdt[5].base_mid    = (tss_base >> 16) & 0xff;
    gdt[5].access      = 0x89;  /* P=1, DPL=0, Type=9 (64-bit TSS available) */
    gdt[5].granularity = ((tss_limit>>16)&0x0f);
    gdt[5].base_high   = (tss_base >> 24) & 0xff;

    /* TSS: point RSP0 to top of kernel stack */
    tss.rsp0       = (u64)ring0_stack + stack_size;
    tss.iopb_offset= sizeof(tss);

    /* Load GDT */
    struct { u16 limit; u64 base; } __attribute__((packed)) gdtr = {
        .limit = sizeof(gdt) - 1,
        .base  = (u64)gdt
    };
    __asm__ volatile("lgdt %0" : : "m"(gdtr));

    /* Reload segments */
    __asm__ volatile(
        "movw $0x10, %%ax\n"   /* Kernel data selector */
        "movw %%ax, %%ds\n"
        "movw %%ax, %%es\n"
        "movw %%ax, %%ss\n"
        "movw $0x00, %%ax\n"
        "movw %%ax, %%fs\n"
        "movw %%ax, %%gs\n"
        "pushq $0x08\n"        /* Kernel code selector */
        "leaq 1f(%%rip), %%rax\n"
        "pushq %%rax\n"
        "lretq\n"
        "1:\n"
        ::: "rax", "memory"
    );

    /* Load TSS */
    __asm__ volatile("ltr %%ax" : : "a"(0x28) : "memory"); /* selector = 5*8 */
}
"""

IDT_C = r"""
/* =========================================================================
 * idt.c — Interrupt Descriptor Table (x86-64)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define IDT_ENTRIES 256

struct idt_entry {
    u16 offset_low;
    u16 selector;     /* Kernel code selector = 0x08 */
    u8  ist;          /* IST index (0 = use RSP0) */
    u8  type_attr;    /* P DPL 0 TYPE */
    u16 offset_mid;
    u32 offset_high;
    u32 zero;
} __attribute__((packed));

static struct idt_entry idt[IDT_ENTRIES] KS_CACHE_LINE_ALIGNED;

/* Handler function pointer type */
typedef void (*ks_isr_handler_t)(u64 vector, u64 error_code, void *frame);
static ks_isr_handler_t isr_table[IDT_ENTRIES];

static void idt_set_gate(u8 vec, u64 handler, u8 ist, u8 dpl) {
    idt[vec].offset_low  = handler & 0xffff;
    idt[vec].selector    = 0x08;          /* Kernel code segment */
    idt[vec].ist         = ist & 0x7;
    idt[vec].type_attr   = 0x80 | ((dpl & 3) << 5) | 0x0e; /* P | DPL | 64-bit gate */
    idt[vec].offset_mid  = (handler >> 16) & 0xffff;
    idt[vec].offset_high = (handler >> 32) & 0xffffffff;
    idt[vec].zero        = 0;
}

void idt_set_handler(u8 vector, ks_isr_handler_t handler) {
    isr_table[vector] = handler;
}

/* Default unhandled interrupt — log and halt */
static void ks_default_isr(u64 vector, u64 ec, void *frame) {
    printk(KERN_ERR "[KS-IDT] Unhandled vector %llu (ec=%llx)\n",
           (unsigned long long)vector, (unsigned long long)ec);
    for (;;) KS_PAUSE();
}

/* C-level dispatcher called from ISR stubs */
void ks_isr_dispatch(u64 vector, u64 error_code, void *frame) {
    ks_isr_handler_t h = isr_table[vector];
    if (KS_LIKELY(h != NULL))
        h(vector, error_code, frame);
    else
        ks_default_isr(vector, error_code, frame);
}

void idt_init(void) {
    /* Fill all slots with default handler address */
    for (int i = 0; i < IDT_ENTRIES; i++) {
        isr_table[i] = ks_default_isr;
        /* Stub address placeholder — real stubs generated by ks_isr_stubs.S */
        idt_set_gate((u8)i, 0, 0, 0);
    }

    struct { u16 limit; u64 base; } __attribute__((packed)) idtr = {
        .limit = sizeof(idt) - 1,
        .base  = (u64)idt
    };
    __asm__ volatile("lidt %0" : : "m"(idtr) : "memory");
}
"""

SCHEDULER_C = r"""
/* =========================================================================
 * scheduler.c — Simple preemptive round-robin scheduler
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define KS_MAX_TASKS   64
#define KS_STACK_SIZE  (16 * 1024)  /* 16 KiB per task */

typedef enum { TASK_UNUSED=0, TASK_READY, TASK_RUNNING, TASK_BLOCKED } ks_task_state_t;

typedef struct ks_task {
    u64              rsp;          /* Saved stack pointer */
    u64              rip;          /* Entry point (only for new tasks) */
    ks_task_state_t  state;
    u32              pid;
    u32              priority;     /* 0 = highest */
    u64              ticks;        /* Time slices consumed */
    char             name[32];
    u8              *stack;
} ks_task_t;

static ks_task_t   tasks[KS_MAX_TASKS] KS_CACHE_LINE_ALIGNED;
static u32         current_pid = 0;
static u32         next_pid    = 1;
static ks_spinlock_t sched_lock;

/* Context switch — saves caller's RSP, loads target RSP */
extern void ks_context_switch(u64 *save_rsp, u64 new_rsp);

__asm__(
    ".globl ks_context_switch\n"
    "ks_context_switch:\n"
    "    pushq %rbp\n"
    "    pushq %rbx\n"
    "    pushq %r12\n"
    "    pushq %r13\n"
    "    pushq %r14\n"
    "    pushq %r15\n"
    "    movq  %rsp, (%rdi)\n"   /* save RSP into *save_rsp */
    "    movq  %rsi, %rsp\n"     /* load new RSP */
    "    popq  %r15\n"
    "    popq  %r14\n"
    "    popq  %r13\n"
    "    popq  %r12\n"
    "    popq  %rbx\n"
    "    popq  %rbp\n"
    "    ret\n"
);

static void task_entry_wrapper(void (*fn)(void)) {
    fn();
    /* Task returned — mark as unused and yield */
    tasks[current_pid].state = TASK_UNUSED;
    for (;;) { __asm__ volatile("hlt"); }
}

u32 ks_task_create(const char *name, void (*entry)(void), u32 priority) {
    ks_spin_lock(&sched_lock);
    for (u32 i = 1; i < KS_MAX_TASKS; i++) {
        if (tasks[i].state == TASK_UNUSED) {
            tasks[i].stack = (u8*)kmalloc(KS_STACK_SIZE, GFP_KERNEL);
            if (!tasks[i].stack) { ks_spin_unlock(&sched_lock); return 0; }

            /* Build initial stack frame */
            u64 *sp = (u64*)(tasks[i].stack + KS_STACK_SIZE);
            *--sp = (u64)entry;             /* arg to wrapper */
            *--sp = (u64)task_entry_wrapper;/* "return address" */
            /* Callee-saved registers (zeroed) */
            for (int r = 0; r < 6; r++) *--sp = 0;

            tasks[i].rsp      = (u64)sp;
            tasks[i].pid      = next_pid++;
            tasks[i].priority = priority;
            tasks[i].ticks    = 0;
            tasks[i].state    = TASK_READY;
            __builtin_strncpy(tasks[i].name, name, 31);
            tasks[i].name[31] = '\0';

            ks_spin_unlock(&sched_lock);
            return tasks[i].pid;
        }
    }
    ks_spin_unlock(&sched_lock);
    return 0; /* no free slot */
}

/* Called from timer ISR — picks next READY task, round-robin */
void ks_schedule(void) {
    u32 cur  = current_pid;
    u32 next = (cur + 1) % KS_MAX_TASKS;
    u32 checked = 0;

    while (checked < KS_MAX_TASKS) {
        if (tasks[next].state == TASK_READY && next != cur) break;
        next = (next + 1) % KS_MAX_TASKS;
        checked++;
    }
    if (next == cur || tasks[next].state != TASK_READY) return;

    if (tasks[cur].state == TASK_RUNNING)
        tasks[cur].state = TASK_READY;
    tasks[next].state = TASK_RUNNING;
    tasks[next].ticks++;
    current_pid = next;

    ks_context_switch(&tasks[cur].rsp, tasks[next].rsp);
}

void ks_scheduler_init(void) {
    spin_lock_init(&sched_lock);
    ks_memset_fast(tasks, 0, sizeof(tasks));
    tasks[0].state = TASK_RUNNING;
    tasks[0].pid   = 0;
    __builtin_strncpy(tasks[0].name, "idle", 4);
    current_pid = 0;
}
"""

VMEM_C = r"""
/* =========================================================================
 * vmem.c — Virtual Memory / Paging (x86-64, 4-level PT)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define PAGE_PRESENT   (1ULL << 0)
#define PAGE_WRITE     (1ULL << 1)
#define PAGE_USER      (1ULL << 2)
#define PAGE_HUGE      (1ULL << 7)
#define PAGE_NX        (1ULL << 63)
#define PAGE_ADDR_MASK 0x000ffffffffff000ULL

typedef u64 pte_t;

/* Simple physical page allocator — you replace with real PMM */
static u64 _phys_next = 0x200000; /* start above 2 MiB */
static u64 ks_alloc_phys_page(void) {
    u64 p = _phys_next;
    _phys_next += KS_PAGE_SIZE;
    return p;
}

/* In a real kernel: use phys_to_virt() / HHDM */
#define PHYS_TO_VIRT(p) ((pte_t *)(p))

static pte_t *ks_pte_get_or_create(pte_t *table, u64 idx, u64 flags) {
    if (!(table[idx] & PAGE_PRESENT)) {
        u64 new_page = ks_alloc_phys_page();
        ks_memset_fast(PHYS_TO_VIRT(new_page), 0, KS_PAGE_SIZE);
        table[idx] = new_page | flags | PAGE_PRESENT;
    }
    return PHYS_TO_VIRT(table[idx] & PAGE_ADDR_MASK);
}

void ks_map_page(pte_t *pml4, u64 virt, u64 phys, u64 flags) {
    u64 idx4 = (virt >> 39) & 0x1ff;
    u64 idx3 = (virt >> 30) & 0x1ff;
    u64 idx2 = (virt >> 21) & 0x1ff;
    u64 idx1 = (virt >> 12) & 0x1ff;

    pte_t *pdp = ks_pte_get_or_create(pml4, idx4, PAGE_WRITE | PAGE_USER);
    pte_t *pd  = ks_pte_get_or_create(pdp,  idx3, PAGE_WRITE | PAGE_USER);
    pte_t *pt  = ks_pte_get_or_create(pd,   idx2, PAGE_WRITE | PAGE_USER);
    pt[idx1]   = (phys & PAGE_ADDR_MASK) | flags | PAGE_PRESENT;

    ks_invlpg((void *)virt);
}

u64 ks_virt_to_phys(pte_t *pml4, u64 virt) {
    u64 idx4 = (virt >> 39) & 0x1ff;
    u64 idx3 = (virt >> 30) & 0x1ff;
    u64 idx2 = (virt >> 21) & 0x1ff;
    u64 idx1 = (virt >> 12) & 0x1ff;

    if (!(pml4[idx4] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pdp = PHYS_TO_VIRT(pml4[idx4] & PAGE_ADDR_MASK);
    if (!(pdp [idx3] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pd  = PHYS_TO_VIRT(pdp [idx3] & PAGE_ADDR_MASK);
    if (!(pd  [idx2] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pt  = PHYS_TO_VIRT(pd  [idx2] & PAGE_ADDR_MASK);
    if (!(pt  [idx1] & PAGE_PRESENT)) return (u64)-1;
    return (pt[idx1] & PAGE_ADDR_MASK) | (virt & 0xfff);
}

pte_t *ks_vmem_new_space(void) {
    u64 phys = ks_alloc_phys_page();
    pte_t *pml4 = PHYS_TO_VIRT(phys);
    ks_memset_fast(pml4, 0, KS_PAGE_SIZE);
    return pml4;
}

void ks_vmem_switch(pte_t *pml4) {
    u64 phys = (u64)pml4; /* assuming identity map for kernel */
    __asm__ volatile("movq %0, %%cr3" : : "r"(phys) : "memory");
}
"""

SYSCALL_C = r"""
/* =========================================================================
 * syscall_dispatch.c — KentScript userland syscall handler (SYSCALL MSR)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define KS_SYS_EXIT    0
#define KS_SYS_WRITE   1
#define KS_SYS_READ    2
#define KS_SYS_MMAP    3
#define KS_SYS_MUNMAP  4
#define KS_SYS_GETPID  5
#define KS_SYS_YIELD   6
#define KS_SYS_MAX     7

typedef long (*ks_syscall_fn_t)(u64, u64, u64, u64, u64, u64);
static ks_syscall_fn_t ks_syscall_table[KS_SYS_MAX];

static long ks_sys_exit(u64 code, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) {
    printk(KERN_INFO "[KS-SYSCALL] exit(%llu)\n", (unsigned long long)code);
    for (;;) __asm__ volatile("hlt");
    return 0;
}
static long ks_sys_write(u64 fd, u64 buf, u64 len, u64 a3, u64 a4, u64 a5) {
    if (fd == 1 || fd == 2)
        return ks_syscall3(1, (long)fd, (long)buf, (long)len); /* Linux write */
    return -1;
}
static long ks_sys_getpid(u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) { return 1; }
static long ks_sys_yield (u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) {
    extern void ks_schedule(void); ks_schedule(); return 0; }

/* Main C-level syscall handler — called from SYSCALL entry stub */
long ks_handle_syscall(u64 nr, u64 a0, u64 a1, u64 a2, u64 a3, u64 a4) {
    if (KS_UNLIKELY(nr >= KS_SYS_MAX || !ks_syscall_table[nr])) return -38; /* ENOSYS */
    return ks_syscall_table[nr](a0, a1, a2, a3, a4, 0);
}

void ks_syscall_init(void) {
    ks_syscall_table[KS_SYS_EXIT]   = ks_sys_exit;
    ks_syscall_table[KS_SYS_WRITE]  = ks_sys_write;
    ks_syscall_table[KS_SYS_GETPID] = ks_sys_getpid;
    ks_syscall_table[KS_SYS_YIELD]  = ks_sys_yield;

#ifdef KS_ARCH_X86_64
    /* Enable SYSCALL/SYSRET via EFER MSR */
    extern u64 ks_rdmsr(u32); extern void ks_wrmsr(u32, u64);
    u64 efer = ks_rdmsr(0xC0000080);
    ks_wrmsr(0xC0000080, efer | 1);            /* SCE bit */
    ks_wrmsr(0xC0000081, 0x0023000800000000ULL);/* STAR: user/kernel CS */
    /* LSTAR = entry point — set by caller with real ASM stub address */
    printk(KERN_INFO "[KS-SYSCALL] SYSCALL MSR configured\n");
#endif
}
"""

# ---------------------------------------------------------------------------
# Write files
# ---------------------------------------------------------------------------

def install(dest: str = ".") -> None:
    d = Path(dest)
    d.mkdir(parents=True, exist_ok=True)

    kernel_dir = d / "minios"
    kernel_dir.mkdir(exist_ok=True)

    files = {
        "ks_kernel_dev.py":        __file__,  # self
        d / "gdt.c":               GDT_C,
        d / "idt.c":               IDT_C,
        d / "scheduler.c":         SCHEDULER_C,
        d / "vmem.c":              VMEM_C,
        d / "syscall_dispatch.c":  SYSCALL_C,
    }

    for path, content in files.items():
        if path == "ks_kernel_dev.py":
            continue
        Path(path).write_text(
            textwrap.dedent(content).lstrip(), encoding="utf-8"
        )
        print(f"  wrote {path}")

    print("\n[KernelDevMode] ✓ All kernel subsystem files installed.")

if __name__ == "__main__":
    import sys
    dest = sys.argv[1] if len(sys.argv) > 1 else "."
    install(dest)
