/* Generated by KentScript Typed C Transpiler - STRICT MODE */
/* Type checking enforced at compile-time by GCC/Clang */
/* No implicit conversions - No silent fallthrough - Deterministic output */

#include "ks_typesystem.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* STRICT MODE: All conversions explicit, all returns checked */

/* Dict hash table */
typedef struct _ks_dict_node {
    char key[64];
    long long val;
    int is_str;
    struct _ks_dict_node* next;
} _ks_dict_node;
typedef struct { _ks_dict_node* buckets[32]; } _ks_dict;

static unsigned int _ks_hash(const char* s) {
    unsigned int h = 0;
    while (*s) h = h * 31 + *s++;
    return h % 32;
}

static _ks_dict* _ks_dict_new(void) {
    _ks_dict* d = malloc(sizeof(_ks_dict));
    memset(d, 0, sizeof(_ks_dict));
    return d;
}

static void _ks_dict_set(_ks_dict* d, const char* key, long long val, int is_str) {
    unsigned int h = _ks_hash(key);
    _ks_dict_node* n = d->buckets[h];
    if (!n) {
        n = malloc(sizeof(_ks_dict_node));
        strncpy(n->key, key, 63); n->key[63] = 0;
        n->val = val; n->is_str = is_str; n->next = NULL;
        d->buckets[h] = n;
    }
}

static long long _ks_dict_get(_ks_dict* d, const char* key, int* found) {
    unsigned int h = _ks_hash(key);
    _ks_dict_node* n = d->buckets[h];
    if (n && strcmp(n->key, key) == 0) { *found = 1; return n->val; }
    *found = 0; return 0;
}

static long long _ks_dict_get_simple(_ks_dict* d, const char* key) {
    int found; return _ks_dict_get(d, key, &found);
}

static _ks_dict* _ks_dict_create(const char* k1, long long v1, int s1, const char* k2, long long v2, int s2) {
    _ks_dict* d = _ks_dict_new();
    _ks_dict_set(d, k1, v1, s1);
    _ks_dict_set(d, k2, v2, s2);
    return d;
}

/* I/O support functions */
static int system_file_write_text(const char* path, const char* content) {
    FILE* f = fopen(path, "w");
    if (!f) return 0;
    fputs(content, f);
    fclose(f);
    return 1;
}

static int system_file_rename(const char* old_path, const char* new_path) {
    return rename(old_path, new_path) == 0;
}

static int system_file_remove(const char* path) {
    return remove(path) == 0;
}

static int system_subprocess_run(const char* cmd) {
    return system(cmd);
}

/* Set hash table */
typedef struct _ks_set_node {
    long long val;
    struct _ks_set_node* next;
} _ks_set_node;
typedef struct { _ks_set_node* buckets[32]; } _ks_set;

static unsigned int _ks_hash_int(long long v) {
    return (unsigned int)(v % 32);
}

static _ks_set* _ks_set_new(void) {
    _ks_set* s = malloc(sizeof(_ks_set));
    memset(s, 0, sizeof(_ks_set));
    return s;
}

static void _ks_set_add(_ks_set* s, long long val) {
    unsigned int h = _ks_hash_int(val);
    _ks_set_node* n = s->buckets[h];
    while (n) {
        if (n->val == val) return;
        n = n->next;
    }
    n = malloc(sizeof(_ks_set_node));
    n->val = val; n->next = s->buckets[h];
    s->buckets[h] = n;
}

static int _ks_set_contains(_ks_set* s, long long val) {
    unsigned int h = _ks_hash_int(val);
    _ks_set_node* n = s->buckets[h];
    while (n) {
        if (n->val == val) return 1;
        n = n->next;
    }
    return 0;
}

KS_FUNC(ks_i64, do_msg, void) {
    MemberAccess(obj=Identifier(name='gui', line=24, col=5), member='message_box', line=24, col=8)("KentScript", "GUI works!", "info");
    /* STRICT ERROR: Missing return statement */
    KS_UNREACHABLE();
}

KS_FUNC(ks_i64, show_text, void) {
    ks_i64 txt = MemberAccess(obj=Identifier(name='gui', line=16, col=15), member='get_text', line=16, col=18)(entry);
    MemberAccess(obj=Identifier(name='gui', line=17, col=5), member='set_text', line=17, col=8)(result_lbl, ("You typed: " + txt));
    /* STRICT ERROR: Missing return statement */
    KS_UNREACHABLE();
}

MemberAccess(obj=Identifier(name='gui', line=7, col=1), member='pack', line=7, col=4)(lbl);
MemberAccess(obj=Identifier(name='gui', line=10, col=1), member='pack', line=10, col=4)(entry);
MemberAccess(obj=Identifier(name='gui', line=13, col=1), member='pack', line=13, col=4)(result_lbl);
MemberAccess(obj=Identifier(name='gui', line=21, col=1), member='pack', line=21, col=4)(btn);
MemberAccess(obj=Identifier(name='gui', line=28, col=1), member='pack', line=28, col=4)(btn2);
MemberAccess(obj=Identifier(name='gui', line=30, col=1), member='mainloop', line=30, col=4)(win);
ks_i64 btn;
ks_i64 btn2;
ks_i64 entry;
ks_i64 lbl;
ks_i64 result_lbl;
ks_i64 win;

void _ks_init_globals(void) {
    btn = MemberAccess(obj=Identifier(name='gui', line=20, col=11), member='create_button', line=20, col=14)(win, "Show Text", show_text);
    btn2 = MemberAccess(obj=Identifier(name='gui', line=27, col=12), member='create_button', line=27, col=15)(win, "Message", do_msg);
    entry = MemberAccess(obj=Identifier(name='gui', line=9, col=13), member='create_entry', line=9, col=16)(win);
    lbl = MemberAccess(obj=Identifier(name='gui', line=6, col=11), member='create_label', line=6, col=14)(win, "Hello from KentScript!");
    result_lbl = MemberAccess(obj=Identifier(name='gui', line=12, col=18), member='create_label', line=12, col=21)(win, "Type something:");
    win = MemberAccess(obj=Identifier(name='gui', line=4, col=11), member='create_window', line=4, col=14)("KentScript GUI Demo", 350, 250);
}

int main(void) {
    _ks_init_globals();
    MemberAccess(obj=Identifier(name='gui', line=7, col=1), member='pack', line=7, col=4)(lbl);
    MemberAccess(obj=Identifier(name='gui', line=10, col=1), member='pack', line=10, col=4)(entry);
    MemberAccess(obj=Identifier(name='gui', line=13, col=1), member='pack', line=13, col=4)(result_lbl);
    MemberAccess(obj=Identifier(name='gui', line=21, col=1), member='pack', line=21, col=4)(btn);
    MemberAccess(obj=Identifier(name='gui', line=28, col=1), member='pack', line=28, col=4)(btn2);
    MemberAccess(obj=Identifier(name='gui', line=30, col=1), member='mainloop', line=30, col=4)(win);
    return 0;
}