/* Generated by KentScript Typed C Transpiler - STRICT MODE */
/* Type checking enforced at compile-time by GCC/Clang */
/* No implicit conversions - No silent fallthrough - Deterministic output */

#include "ks_typesystem.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

/* STRICT MODE: All conversions explicit, all returns checked */

/* Dict hash table */
typedef struct _ks_dict_node {
    char key[64];
    long long val;
    int is_str;
    struct _ks_dict_node* next;
} _ks_dict_node;
typedef struct { _ks_dict_node* buckets[32]; } _ks_dict;

static unsigned int _ks_hash(const char* s) {
    unsigned int h = 0;
    while (*s) h = h * 31 + *s++;
    return h % 32;
}

static _ks_dict* _ks_dict_new(void) {
    _ks_dict* d = malloc(sizeof(_ks_dict));
    memset(d, 0, sizeof(_ks_dict));
    return d;
}

static void _ks_dict_set(_ks_dict* d, const char* key, long long val, int is_str) {
    unsigned int h = _ks_hash(key);
    _ks_dict_node* n = d->buckets[h];
    if (!n) {
        n = malloc(sizeof(_ks_dict_node));
        strncpy(n->key, key, 63); n->key[63] = 0;
        n->val = val; n->is_str = is_str; n->next = NULL;
        d->buckets[h] = n;
    }
}

static long long _ks_dict_get(_ks_dict* d, const char* key, int* found) {
    unsigned int h = _ks_hash(key);
    _ks_dict_node* n = d->buckets[h];
    if (n && strcmp(n->key, key) == 0) { *found = 1; return n->val; }
    *found = 0; return 0;
}

static long long _ks_dict_get_simple(_ks_dict* d, const char* key) {
    int found; return _ks_dict_get(d, key, &found);
}

static _ks_dict* _ks_dict_create(const char* k1, long long v1, int s1, const char* k2, long long v2, int s2) {
    _ks_dict* d = _ks_dict_new();
    _ks_dict_set(d, k1, v1, s1);
    _ks_dict_set(d, k2, v2, s2);
    return d;
}

/* I/O support functions */
static int system_file_write_text(const char* path, const char* content) {
    FILE* f = fopen(path, "w");
    if (!f) return 0;
    fputs(content, f);
    fclose(f);
    return 1;
}

static int system_file_rename(const char* old_path, const char* new_path) {
    return rename(old_path, new_path) == 0;
}

static int system_file_remove(const char* path) {
    return remove(path) == 0;
}

static int system_subprocess_run(const char* cmd) {
    return system(cmd);
}

/* Set hash table */
typedef struct _ks_set_node {
    long long val;
    struct _ks_set_node* next;
} _ks_set_node;
typedef struct { _ks_set_node* buckets[32]; } _ks_set;

static unsigned int _ks_hash_int(long long v) {
    return (unsigned int)(v % 32);
}

static _ks_set* _ks_set_new(void) {
    _ks_set* s = malloc(sizeof(_ks_set));
    memset(s, 0, sizeof(_ks_set));
    return s;
}

static void _ks_set_add(_ks_set* s, long long val) {
    unsigned int h = _ks_hash_int(val);
    _ks_set_node* n = s->buckets[h];
    while (n) {
        if (n->val == val) return;
        n = n->next;
    }
    n = malloc(sizeof(_ks_set_node));
    n->val = val; n->next = s->buckets[h];
    s->buckets[h] = n;
}

static int _ks_set_contains(_ks_set* s, long long val) {
    unsigned int h = _ks_hash_int(val);
    _ks_set_node* n = s->buckets[h];
    while (n) {
        if (n->val == val) return 1;
        n = n->next;
    }
    return 0;
}

printf("%s\n", _ks_str_int("=== KentScript Low-Level Features Demo ==="));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("1. Type Aliases:"));
printf("%s\n", _ks_str_int(("  int: " + str(count))));
printf("%s\n", _ks_str_int(("  uint: " + str(size))));
printf("%s\n", _ks_str_int(("  float: " + str(ratio))));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("2. F-String Interpolation:"));
printf("%s\n", _ks_str_int(((("  " + str(lang)) + " was created in ") + str(year))));
printf("%s\n", _ks_str_int(("  Expression: 2 + 2 = " + str((2 + 2)))));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("3. Tuple Destructuring:"));
printf("%s\n", _ks_str_int(((((("  x=" + str(x)) + ", y=") + str(y)) + ", z=") + str(z))));
printf("%s\n", _ks_str_int(((("  a=" + str(a)) + ", b=") + str(b))));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("4. Arrays:"));
printf("%s\n", _ks_str_int(("  Array: " + str(numbers))));
printf("%s\n", _ks_str_int(("  First element: " + str(_ks_dict_get_simple(0, 0)))));
printf("%s\n", _ks_str_int(("  Last element: " + str(_ks_dict_get_simple(0, 4)))));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("5. Low-Level Operations (unsafe block):"));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("6. Combined Example:"));
printf("%s\n", _ks_str_int(("  Original value: " + str(data))));
printf("%s\n", _ks_str_int(""));
printf("%s\n", _ks_str_int("=== All Features Working! ==="));
ks_i64 __tuple_destructure__a,b = 0;
ks_i64 __tuple_destructure__x,y,z = 0;
ks_i64 count = 42;
ks_i64 data = "0xDEADBEEF";
ks_i64 lang = "KentScript";
ks_i64[] numbers = {1, 2, 3, 4, 5};
ks_f64 ratio = 3.14159;
ks_u64 size = 1024;
ks_i64 year = 2024;

int main(void) {
    printf("%s\n", _ks_str_int("=== KentScript Low-Level Features Demo ==="));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("1. Type Aliases:"));
    printf("%s\n", _ks_str_int(("  int: " + str(count))));
    printf("%s\n", _ks_str_int(("  uint: " + str(size))));
    printf("%s\n", _ks_str_int(("  float: " + str(ratio))));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("2. F-String Interpolation:"));
    printf("%s\n", _ks_str_int(((("  " + str(lang)) + " was created in ") + str(year))));
    printf("%s\n", _ks_str_int(("  Expression: 2 + 2 = " + str((2 + 2)))));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("3. Tuple Destructuring:"));
    printf("%s\n", _ks_str_int(((((("  x=" + str(x)) + ", y=") + str(y)) + ", z=") + str(z))));
    printf("%s\n", _ks_str_int(((("  a=" + str(a)) + ", b=") + str(b))));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("4. Arrays:"));
    printf("%s\n", _ks_str_int(("  Array: " + str(numbers))));
    printf("%s\n", _ks_str_int(("  First element: " + str(_ks_dict_get_simple(0, 0)))));
    printf("%s\n", _ks_str_int(("  Last element: " + str(_ks_dict_get_simple(0, 4)))));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("5. Low-Level Operations (unsafe block):"));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("6. Combined Example:"));
    printf("%s\n", _ks_str_int(("  Original value: " + str(data))));
    printf("%s\n", _ks_str_int(""));
    printf("%s\n", _ks_str_int("=== All Features Working! ==="));
    return 0;
}