/* =========================================================================
 * gdt.c — Global Descriptor Table (x86-64, flat 64-bit model)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

/* GDT entry (8 bytes) */
struct gdt_entry {
    u16 limit_low;
    u16 base_low;
    u8  base_mid;
    u8  access;     /* P DPL S E DC RW A */
    u8  granularity;/* G DB L AVL limit_high(4) */
    u8  base_high;
} __attribute__((packed));

/* 64-bit TSS needs 16 bytes */
struct tss_entry {
    u32 reserved0;
    u64 rsp0;   /* Ring-0 stack pointer (loaded on interrupt) */
    u64 rsp1;
    u64 rsp2;
    u64 reserved1;
    u64 ist[7]; /* Interrupt stack table */
    u64 reserved2;
    u16 reserved3;
    u16 iopb_offset;
} __attribute__((packed));

#define GDT_ENTRIES 6
static struct gdt_entry gdt[GDT_ENTRIES] KS_CACHE_LINE_ALIGNED;
static struct tss_entry tss             KS_CACHE_LINE_ALIGNED;

static void gdt_set_entry(int idx, u32 base, u32 limit, u8 access, u8 gran) {
    gdt[idx].base_low   = base & 0xffff;
    gdt[idx].base_mid   = (base >> 16) & 0xff;
    gdt[idx].base_high  = (base >> 24) & 0xff;
    gdt[idx].limit_low  = limit & 0xffff;
    gdt[idx].granularity= ((limit >> 16) & 0x0f) | (gran & 0xf0);
    gdt[idx].access     = access;
}

void gdt_init(void *ring0_stack, size_t stack_size) {
    /* 0: null descriptor */
    gdt_set_entry(0, 0, 0,          0,    0);
    /* 1: kernel code — 64-bit, DPL 0 */
    gdt_set_entry(1, 0, 0xffffffff, 0x9a, 0xa0);
    /* 2: kernel data — DPL 0 */
    gdt_set_entry(2, 0, 0xffffffff, 0x92, 0xcf);
    /* 3: user code  — 64-bit, DPL 3 */
    gdt_set_entry(3, 0, 0xffffffff, 0xfa, 0xa0);
    /* 4: user data  — DPL 3 */
    gdt_set_entry(4, 0, 0xffffffff, 0xf2, 0xcf);
    /* 5: TSS descriptor (lower 8 bytes) — set separately */
    u64 tss_base  = (u64)&tss;
    u32 tss_limit = sizeof(tss) - 1;
    gdt[5].limit_low   = tss_limit & 0xffff;
    gdt[5].base_low    = tss_base  & 0xffff;
    gdt[5].base_mid    = (tss_base >> 16) & 0xff;
    gdt[5].access      = 0x89;  /* P=1, DPL=0, Type=9 (64-bit TSS available) */
    gdt[5].granularity = ((tss_limit>>16)&0x0f);
    gdt[5].base_high   = (tss_base >> 24) & 0xff;

    /* TSS: point RSP0 to top of kernel stack */
    tss.rsp0       = (u64)ring0_stack + stack_size;
    tss.iopb_offset= sizeof(tss);

    /* Load GDT */
    struct { u16 limit; u64 base; } __attribute__((packed)) gdtr = {
        .limit = sizeof(gdt) - 1,
        .base  = (u64)gdt
    };
    __asm__ volatile("lgdt %0" : : "m"(gdtr));

    /* Reload segments */
    __asm__ volatile(
        "movw $0x10, %%ax\n"   /* Kernel data selector */
        "movw %%ax, %%ds\n"
        "movw %%ax, %%es\n"
        "movw %%ax, %%ss\n"
        "movw $0x00, %%ax\n"
        "movw %%ax, %%fs\n"
        "movw %%ax, %%gs\n"
        "pushq $0x08\n"        /* Kernel code selector */
        "leaq 1f(%%rip), %%rax\n"
        "pushq %%rax\n"
        "lretq\n"
        "1:\n"
        ::: "rax", "memory"
    );

    /* Load TSS */
    __asm__ volatile("ltr %%ax" : : "a"(0x28) : "memory"); /* selector = 5*8 */
}
