/* =========================================================================
 * idt.c — Interrupt Descriptor Table (x86-64)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define IDT_ENTRIES 256

struct idt_entry {
    u16 offset_low;
    u16 selector;     /* Kernel code selector = 0x08 */
    u8  ist;          /* IST index (0 = use RSP0) */
    u8  type_attr;    /* P DPL 0 TYPE */
    u16 offset_mid;
    u32 offset_high;
    u32 zero;
} __attribute__((packed));

static struct idt_entry idt[IDT_ENTRIES] KS_CACHE_LINE_ALIGNED;

/* Handler function pointer type */
typedef void (*ks_isr_handler_t)(u64 vector, u64 error_code, void *frame);
static ks_isr_handler_t isr_table[IDT_ENTRIES];

static void idt_set_gate(u8 vec, u64 handler, u8 ist, u8 dpl) {
    idt[vec].offset_low  = handler & 0xffff;
    idt[vec].selector    = 0x08;          /* Kernel code segment */
    idt[vec].ist         = ist & 0x7;
    idt[vec].type_attr   = 0x80 | ((dpl & 3) << 5) | 0x0e; /* P | DPL | 64-bit gate */
    idt[vec].offset_mid  = (handler >> 16) & 0xffff;
    idt[vec].offset_high = (handler >> 32) & 0xffffffff;
    idt[vec].zero        = 0;
}

void idt_set_handler(u8 vector, ks_isr_handler_t handler) {
    isr_table[vector] = handler;
}

/* Default unhandled interrupt — log and halt */
static void ks_default_isr(u64 vector, u64 ec, void *frame) {
    printk(KERN_ERR "[KS-IDT] Unhandled vector %llu (ec=%llx)\n",
           (unsigned long long)vector, (unsigned long long)ec);
    for (;;) KS_PAUSE();
}

/* C-level dispatcher called from ISR stubs */
void ks_isr_dispatch(u64 vector, u64 error_code, void *frame) {
    ks_isr_handler_t h = isr_table[vector];
    if (KS_LIKELY(h != NULL))
        h(vector, error_code, frame);
    else
        ks_default_isr(vector, error_code, frame);
}

void idt_init(void) {
    /* Fill all slots with default handler address */
    for (int i = 0; i < IDT_ENTRIES; i++) {
        isr_table[i] = ks_default_isr;
        /* Stub address placeholder — real stubs generated by ks_isr_stubs.S */
        idt_set_gate((u8)i, 0, 0, 0);
    }

    struct { u16 limit; u64 base; } __attribute__((packed)) idtr = {
        .limit = sizeof(idt) - 1,
        .base  = (u64)idt
    };
    __asm__ volatile("lidt %0" : : "m"(idtr) : "memory");
}
