/* =========================================================================
 * scheduler.c — Simple preemptive round-robin scheduler
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define KS_MAX_TASKS   64
#define KS_STACK_SIZE  (16 * 1024)  /* 16 KiB per task */

typedef enum { TASK_UNUSED=0, TASK_READY, TASK_RUNNING, TASK_BLOCKED } ks_task_state_t;

typedef struct ks_task {
    u64              rsp;          /* Saved stack pointer */
    u64              rip;          /* Entry point (only for new tasks) */
    ks_task_state_t  state;
    u32              pid;
    u32              priority;     /* 0 = highest */
    u64              ticks;        /* Time slices consumed */
    char             name[32];
    u8              *stack;
} ks_task_t;

static ks_task_t   tasks[KS_MAX_TASKS] KS_CACHE_LINE_ALIGNED;
static u32         current_pid = 0;
static u32         next_pid    = 1;
static ks_spinlock_t sched_lock;

/* Context switch — saves caller's RSP, loads target RSP */
extern void ks_context_switch(u64 *save_rsp, u64 new_rsp);

__asm__(
    ".globl ks_context_switch\n"
    "ks_context_switch:\n"
    "    pushq %rbp\n"
    "    pushq %rbx\n"
    "    pushq %r12\n"
    "    pushq %r13\n"
    "    pushq %r14\n"
    "    pushq %r15\n"
    "    movq  %rsp, (%rdi)\n"   /* save RSP into *save_rsp */
    "    movq  %rsi, %rsp\n"     /* load new RSP */
    "    popq  %r15\n"
    "    popq  %r14\n"
    "    popq  %r13\n"
    "    popq  %r12\n"
    "    popq  %rbx\n"
    "    popq  %rbp\n"
    "    ret\n"
);

static void task_entry_wrapper(void (*fn)(void)) {
    fn();
    /* Task returned — mark as unused and yield */
    tasks[current_pid].state = TASK_UNUSED;
    for (;;) { __asm__ volatile("hlt"); }
}

u32 ks_task_create(const char *name, void (*entry)(void), u32 priority) {
    ks_spin_lock(&sched_lock);
    for (u32 i = 1; i < KS_MAX_TASKS; i++) {
        if (tasks[i].state == TASK_UNUSED) {
            tasks[i].stack = (u8*)kmalloc(KS_STACK_SIZE, GFP_KERNEL);
            if (!tasks[i].stack) { ks_spin_unlock(&sched_lock); return 0; }

            /* Build initial stack frame */
            u64 *sp = (u64*)(tasks[i].stack + KS_STACK_SIZE);
            *--sp = (u64)entry;             /* arg to wrapper */
            *--sp = (u64)task_entry_wrapper;/* "return address" */
            /* Callee-saved registers (zeroed) */
            for (int r = 0; r < 6; r++) *--sp = 0;

            tasks[i].rsp      = (u64)sp;
            tasks[i].pid      = next_pid++;
            tasks[i].priority = priority;
            tasks[i].ticks    = 0;
            tasks[i].state    = TASK_READY;
            __builtin_strncpy(tasks[i].name, name, 31);
            tasks[i].name[31] = '\0';

            ks_spin_unlock(&sched_lock);
            return tasks[i].pid;
        }
    }
    ks_spin_unlock(&sched_lock);
    return 0; /* no free slot */
}

/* Called from timer ISR — picks next READY task, round-robin */
void ks_schedule(void) {
    u32 cur  = current_pid;
    u32 next = (cur + 1) % KS_MAX_TASKS;
    u32 checked = 0;

    while (checked < KS_MAX_TASKS) {
        if (tasks[next].state == TASK_READY && next != cur) break;
        next = (next + 1) % KS_MAX_TASKS;
        checked++;
    }
    if (next == cur || tasks[next].state != TASK_READY) return;

    if (tasks[cur].state == TASK_RUNNING)
        tasks[cur].state = TASK_READY;
    tasks[next].state = TASK_RUNNING;
    tasks[next].ticks++;
    current_pid = next;

    ks_context_switch(&tasks[cur].rsp, tasks[next].rsp);
}

void ks_scheduler_init(void) {
    spin_lock_init(&sched_lock);
    ks_memset_fast(tasks, 0, sizeof(tasks));
    tasks[0].state = TASK_RUNNING;
    tasks[0].pid   = 0;
    __builtin_strncpy(tasks[0].name, "idle", 4);
    current_pid = 0;
}
