/* =========================================================================
 * syscall_dispatch.c — KentScript userland syscall handler (SYSCALL MSR)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define KS_SYS_EXIT    0
#define KS_SYS_WRITE   1
#define KS_SYS_READ    2
#define KS_SYS_MMAP    3
#define KS_SYS_MUNMAP  4
#define KS_SYS_GETPID  5
#define KS_SYS_YIELD   6
#define KS_SYS_MAX     7

typedef long (*ks_syscall_fn_t)(u64, u64, u64, u64, u64, u64);
static ks_syscall_fn_t ks_syscall_table[KS_SYS_MAX];

static long ks_sys_exit(u64 code, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) {
    printk(KERN_INFO "[KS-SYSCALL] exit(%llu)\n", (unsigned long long)code);
    for (;;) __asm__ volatile("hlt");
    return 0;
}
static long ks_sys_write(u64 fd, u64 buf, u64 len, u64 a3, u64 a4, u64 a5) {
    if (fd == 1 || fd == 2)
        return ks_syscall3(1, (long)fd, (long)buf, (long)len); /* Linux write */
    return -1;
}
static long ks_sys_getpid(u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) { return 1; }
static long ks_sys_yield (u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5) {
    extern void ks_schedule(void); ks_schedule(); return 0; }

/* Main C-level syscall handler — called from SYSCALL entry stub */
long ks_handle_syscall(u64 nr, u64 a0, u64 a1, u64 a2, u64 a3, u64 a4) {
    if (KS_UNLIKELY(nr >= KS_SYS_MAX || !ks_syscall_table[nr])) return -38; /* ENOSYS */
    return ks_syscall_table[nr](a0, a1, a2, a3, a4, 0);
}

void ks_syscall_init(void) {
    ks_syscall_table[KS_SYS_EXIT]   = ks_sys_exit;
    ks_syscall_table[KS_SYS_WRITE]  = ks_sys_write;
    ks_syscall_table[KS_SYS_GETPID] = ks_sys_getpid;
    ks_syscall_table[KS_SYS_YIELD]  = ks_sys_yield;

#ifdef KS_ARCH_X86_64
    /* Enable SYSCALL/SYSRET via EFER MSR */
    extern u64 ks_rdmsr(u32); extern void ks_wrmsr(u32, u64);
    u64 efer = ks_rdmsr(0xC0000080);
    ks_wrmsr(0xC0000080, efer | 1);            /* SCE bit */
    ks_wrmsr(0xC0000081, 0x0023000800000000ULL);/* STAR: user/kernel CS */
    /* LSTAR = entry point — set by caller with real ASM stub address */
    printk(KERN_INFO "[KS-SYSCALL] SYSCALL MSR configured\n");
#endif
}
