/* =========================================================================
 * vmem.c — Virtual Memory / Paging (x86-64, 4-level PT)
 * Generated by KentScript Kernel Dev Mode
 * ======================================================================= */
#include "ks_runtime.h"

#define PAGE_PRESENT   (1ULL << 0)
#define PAGE_WRITE     (1ULL << 1)
#define PAGE_USER      (1ULL << 2)
#define PAGE_HUGE      (1ULL << 7)
#define PAGE_NX        (1ULL << 63)
#define PAGE_ADDR_MASK 0x000ffffffffff000ULL

typedef u64 pte_t;

/* Simple physical page allocator — you replace with real PMM */
static u64 _phys_next = 0x200000; /* start above 2 MiB */
static u64 ks_alloc_phys_page(void) {
    u64 p = _phys_next;
    _phys_next += KS_PAGE_SIZE;
    return p;
}

/* In a real kernel: use phys_to_virt() / HHDM */
#define PHYS_TO_VIRT(p) ((pte_t *)(p))

static pte_t *ks_pte_get_or_create(pte_t *table, u64 idx, u64 flags) {
    if (!(table[idx] & PAGE_PRESENT)) {
        u64 new_page = ks_alloc_phys_page();
        ks_memset_fast(PHYS_TO_VIRT(new_page), 0, KS_PAGE_SIZE);
        table[idx] = new_page | flags | PAGE_PRESENT;
    }
    return PHYS_TO_VIRT(table[idx] & PAGE_ADDR_MASK);
}

void ks_map_page(pte_t *pml4, u64 virt, u64 phys, u64 flags) {
    u64 idx4 = (virt >> 39) & 0x1ff;
    u64 idx3 = (virt >> 30) & 0x1ff;
    u64 idx2 = (virt >> 21) & 0x1ff;
    u64 idx1 = (virt >> 12) & 0x1ff;

    pte_t *pdp = ks_pte_get_or_create(pml4, idx4, PAGE_WRITE | PAGE_USER);
    pte_t *pd  = ks_pte_get_or_create(pdp,  idx3, PAGE_WRITE | PAGE_USER);
    pte_t *pt  = ks_pte_get_or_create(pd,   idx2, PAGE_WRITE | PAGE_USER);
    pt[idx1]   = (phys & PAGE_ADDR_MASK) | flags | PAGE_PRESENT;

    ks_invlpg((void *)virt);
}

u64 ks_virt_to_phys(pte_t *pml4, u64 virt) {
    u64 idx4 = (virt >> 39) & 0x1ff;
    u64 idx3 = (virt >> 30) & 0x1ff;
    u64 idx2 = (virt >> 21) & 0x1ff;
    u64 idx1 = (virt >> 12) & 0x1ff;

    if (!(pml4[idx4] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pdp = PHYS_TO_VIRT(pml4[idx4] & PAGE_ADDR_MASK);
    if (!(pdp [idx3] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pd  = PHYS_TO_VIRT(pdp [idx3] & PAGE_ADDR_MASK);
    if (!(pd  [idx2] & PAGE_PRESENT)) return (u64)-1;
    pte_t *pt  = PHYS_TO_VIRT(pd  [idx2] & PAGE_ADDR_MASK);
    if (!(pt  [idx1] & PAGE_PRESENT)) return (u64)-1;
    return (pt[idx1] & PAGE_ADDR_MASK) | (virt & 0xfff);
}

pte_t *ks_vmem_new_space(void) {
    u64 phys = ks_alloc_phys_page();
    pte_t *pml4 = PHYS_TO_VIRT(phys);
    ks_memset_fast(pml4, 0, KS_PAGE_SIZE);
    return pml4;
}

void ks_vmem_switch(pte_t *pml4) {
    u64 phys = (u64)pml4; /* assuming identity map for kernel */
    __asm__ volatile("movq %0, %%cr3" : : "r"(phys) : "memory");
}
